using System;
using System.Globalization;
using System.IO;
using System.Text;
using DisasterPlus.Core.Typhoon;
using DisasterPlus.Tools;

namespace DisasterPlus.Tools.TyphoonPreview
{
    /// <summary>
    /// 台風の渦を**ゲームを起動せずに**描いて確かめる。
    ///
    /// 「見た目の変更は自分でオフラインに描画・計測してから実機テストを頼む」という
    /// このプロジェクトの決まりのための道具である。Core の実物
    /// （<see cref="VortexPuffLayout"/> / <see cref="VortexCloudProfile"/>）を
    /// そのままコンパイルして呼ぶので、**書き直した近似ではない**。
    ///
    ///   dotnet run --project tools/TyphoonPreview -- docs/images/typhoon
    ///
    /// 出す絵は 3 枚:
    ///
    /// - <c>vortex-plan.png</c>      真上から。**腕・壁雲・眼の穴**を見る
    /// - <c>vortex-elevation.png</c> 真横から（渦ぜんぶ）。**平らな雲底**を見る
    /// - <c>vortex-eyewall-elevation.png</c> 真横から、眼のまわりに 3 倍寄る。
    ///   **塔の高さともこもこ**を見る
    /// - <c>vortex-oblique.png</c>   ゲームのカメラに近い俯角 35 度。**実機の見え方**
    /// - <c>squall-elevation.png</c> 吹き付ける雨を真横から。**風下へ流れているか**を見る
    /// </summary>
    internal static class Program
    {
        /// <summary>強度 128 の台風の渦の外周半径（m）。
        /// 実機と同じ規則（暴風域半径 × 1.35、6000 m で頭打ち）で出す。</summary>
        private static readonly float Radius =
            Vortex.RadiusOf(TyphoonProfile.StormRadiusOf(128, PrefabRadiusMetres));

        /// <summary><c>ThunderStormAI.m_radius</c>（sharedassets55 の実測値）。</summary>
        private const float PrefabRadiusMetres = 4000f;

        /// <summary>絵の一辺（px）。</summary>
        private const int Pixels = 900;

        /// <summary>渦の外周が画面のどこまでを占めるか。</summary>
        private const float Fill = 0.92f;

        /// <summary>ゲームのカメラに近い俯角（度）。</summary>
        private const float ObliquePitchDegrees = 35f;

        /// <summary>
        /// 1 粒の不透明度の倍率。**推測ではなく実測値である** ——
        /// <c>sharedassets11.assets</c> の <c>steam</c> テクスチャの平均アルファは
        /// 109/255 ＝ 0.43 で、粒子の見かけの濃さは
        /// <c>startColor.a × テクスチャのアルファ</c>になる。
        /// 重なれば足し合わさって不透明になる（実機と同じ）。
        /// </summary>
        private const float SplatAlpha = 0.43f;

        private static readonly float[] Sky = { 0.55f, 0.66f, 0.82f };

        private static readonly float[] Ground = { 0.31f, 0.36f, 0.29f };

        private static int Main(string[] args)
        {
            string outDir = args.Length > 0 ? args[0] : "docs/images/typhoon";
            Directory.CreateDirectory(outDir);

            var log = new StringBuilder();
            log.AppendLine("# Typhoon vortex preview (generated by tools/TyphoonPreview)");
            log.AppendLine();
            log.AppendLine("vortex radius = " + F(Radius) + " m  (intensity 128, storm radius "
                           + F(TyphoonProfile.StormRadiusOf(128, PrefabRadiusMetres))
                           + " m, prefab m_radius " + F(PrefabRadiusMetres) + ")");
            log.AppendLine("cloud thickness = " + F(Vortex.ThicknessMetres) + " m");
            log.AppendLine("columns = " + VortexPuffLayout.ColumnCount
                           + " (eyewall " + VortexPuffLayout.EyeWallColumns
                           + " + arms " + VortexPuffLayout.ArmCount + "x"
                           + VortexPuffLayout.ColumnsPerArm + "), levels = "
                           + VortexPuffLayout.LevelsPerColumn
                           + ", RenderEffect calls/frame = " + VortexPuffLayout.PuffCount);
            log.AppendLine();

            Measure(log);

            Speck[] specks = Vortex.Build(Radius, 0f, 0x54595048u);
            log.AppendLine("particles drawn = " + specks.Length
                           + " (the live cap the game enforces: "
                           + (VortexCloudProfile.Deck.MaxParticles
                              + VortexCloudProfile.Tower.MaxParticles
                              + VortexCloudProfile.Canopy.MaxParticles) + ")");
            log.AppendLine();

            Write(outDir, "vortex-plan.png", Plan(specks));
            Write(outDir, "vortex-elevation.png", Elevation(specks, 1f));
            Write(outDir, "vortex-eyewall-elevation.png", Elevation(specks, 3f));
            Write(outDir, "vortex-oblique.png", Oblique(specks));

            // ★ 暴風雨（横殴りの飛沫）。**カメラの周りに置く**ものなので、
            //   渦とは別の絵にする。カメラの高さ 260 m ＝ 街を見るくらいの引き。
            Speck[] spray = Squall.Build(260f, 1f, 0x53515544u);
            log.AppendLine("driving rain particles drawn = " + spray.Length
                           + " (cap " + SquallLayout.MaxParticles + ", spread "
                           + F(SquallLayout.SpreadFor(260f)) + " m at 260 m camera height, drift "
                           + F(SquallLayout.DriftMetresPerSecond) + " m/s)");
            log.AppendLine();
            Write(outDir, "squall-elevation.png", SquallElevation(spray));

            // ★★ **自前の白い雲で組んだ渦**（2026-08-22 の作り直し）。
            //    借り物の粒子との違いを数字と絵で残す。
            OwnedPuffs(outDir, log);

            File.WriteAllText(Path.Combine(outDir, "measurements.txt"), log.ToString());
            Console.WriteLine("wrote " + Path.Combine(outDir, "measurements.txt"));
            return 0;
        }

        /// <summary>
        /// **自前の白い雲の粒で置いた渦**（<c>TyphoonVortexPuffFx</c>）を、
        /// 真上と俯角 35 度から描く。借り物の粒子と何が違うのかを数字でも出す。
        /// </summary>
        private static void OwnedPuffs(string dir, StringBuilder log)
        {
            OwnedVortex.Puff[] puffs = OwnedVortex.Build(Radius, 0f);

            log.AppendLine("## owned white-cloud puffs (2026-08-22 rebuild)");
            log.AppendLine("  puffs placed per frame = " + puffs.Length
                           + " (was: thousands of borrowed particles, drifting;"
                           + " the first attempt placed only " + VortexPuffLayout.PuffCount + ")");
            log.AppendLine("  texture opacity at the puff core = "
                           + OwnedVortex.CoreOpacity().ToString("F3")
                           + "  (steam, the borrowed material: 0.43)");

            float smallest = float.MaxValue;
            float largest = 0f;
            foreach (OwnedVortex.Puff q in puffs)
            {
                if (q.Radius < smallest) smallest = q.Radius;
                if (q.Radius > largest) largest = q.Radius;
            }
            log.AppendLine("  puff radius = " + F(smallest) + " .. " + F(largest)
                           + " m  (vortex radius " + F(Radius) + " m)");

            // 粒がどれだけ重なっているか。**隙間が空いていないこと**を数で見る。
            float area = 0f;
            foreach (OwnedVortex.Puff q in puffs) area += 3.14159265f * q.Radius * q.Radius;
            log.AppendLine("  puff area / vortex area = "
                           + (area / (3.14159265f * Radius * Radius)).ToString("F2")
                           + "  (below 1.0 would leave holes)");
            log.AppendLine();

            Write(dir, "vortex-owned-plan.png", OwnedPlan(puffs));
            Write(dir, "vortex-owned-oblique.png", OwnedOblique(puffs));
        }

        /// <summary>真上から。腕と眼が読めるか。</summary>
        private static byte[] OwnedPlan(OwnedVortex.Puff[] puffs)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];
            float scale = Pixels * Fill * 0.5f / Radius;
            float half = Pixels * 0.5f;

            // 高いものが上に来る（真上から見るので）。
            Array.Sort(puffs, delegate(OwnedVortex.Puff a, OwnedVortex.Puff b)
            {
                return a.Y.CompareTo(b.Y);
            });

            foreach (OwnedVortex.Puff q in puffs)
            {
                Blob(cover, colour, half + q.X * scale, half + q.Z * scale,
                     q.Radius * scale, q.Alpha, q.Shade);
            }

            return ComposeOwned(cover, colour, false);
        }

        /// <summary>俯角 35 度。実機に近い見え方。</summary>
        private static byte[] OwnedOblique(OwnedVortex.Puff[] puffs)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];
            float scale = Pixels * Fill * 0.5f / Radius;
            float half = Pixels * 0.5f;

            double pitch = ObliquePitchDegrees * Math.PI / 180.0;
            float cos = (float)Math.Cos(pitch);
            float sin = (float)Math.Sin(pitch);

            // 奥のものから描く。
            Array.Sort(puffs, delegate(OwnedVortex.Puff a, OwnedVortex.Puff b)
            {
                float da = a.Z * sin - a.Y * cos;
                float db = b.Z * sin - b.Y * cos;
                return db.CompareTo(da);
            });

            foreach (OwnedVortex.Puff q in puffs)
            {
                float sy = q.Z * sin - q.Y * cos;
                Blob(cover, colour, half + q.X * scale, half * 1.25f + sy * scale,
                     q.Radius * scale, q.Alpha, q.Shade);
            }

            return ComposeOwned(cover, colour, true);
        }

        /// <summary>
        /// 粒 1 個。**テクスチャの式そのもの**で塗る（<c>OwnedVortex.TextureAlpha</c>）。
        /// アルファ合成なので、重ねるほど背景が隠れる。
        /// </summary>
        private static void Blob(float[] cover, float[] colour, float cx, float cy, float r,
                                 float alpha, float shade)
        {
            if (!(r > 0f)) return;

            int x0 = (int)Math.Floor(cx - r), x1 = (int)Math.Ceiling(cx + r);
            int y0 = (int)Math.Floor(cy - r), y1 = (int)Math.Ceiling(cy + r);

            // 日向の白と底面の灰（TyphoonVortexPuffFx と同じ 2 色）。
            float rr = (242f + (150f - 242f) * shade) / 255f;
            float gg = (244f + (156f - 244f) * shade) / 255f;
            float bb = (248f + (170f - 248f) * shade) / 255f;

            for (int y = y0; y <= y1; y++)
            {
                if (y < 0 || y >= Pixels) continue;
                for (int x = x0; x <= x1; x++)
                {
                    if (x < 0 || x >= Pixels) continue;

                    float dx = (x - cx) / r;
                    float dy = (y - cy) / r;
                    float d = (float)Math.Sqrt(dx * dx + dy * dy);
                    if (d > 1f) continue;

                    float a = OwnedVortex.TextureAlpha(d, (float)Math.Atan2(dy, dx)) * alpha;
                    if (a <= 0f) continue;

                    int i = y * Pixels + x;
                    // 手前が奥を隠す（over 合成）。
                    float keep = 1f - a;
                    colour[i * 3] = colour[i * 3] * keep + rr * a;
                    colour[i * 3 + 1] = colour[i * 3 + 1] * keep + gg * a;
                    colour[i * 3 + 2] = colour[i * 3 + 2] * keep + bb * a;
                    cover[i] = cover[i] * keep + a;
                }
            }
        }

        /// <summary>雲を空（と地面）の上に載せる。</summary>
        private static byte[] ComposeOwned(float[] cover, float[] colour, bool horizon)
        {
            var rgb = new byte[Pixels * Pixels * 3];

            for (int y = 0; y < Pixels; y++)
            {
                for (int x = 0; x < Pixels; x++)
                {
                    int i = y * Pixels + x;
                    float[] back = horizon && y > Pixels * 0.78f ? Ground : Sky;

                    float a = cover[i];
                    if (a > 1f) a = 1f;

                    for (int c = 0; c < 3; c++)
                    {
                        float v = back[c] * (1f - a) + colour[i * 3 + c];
                        if (v > 1f) v = 1f;
                        rgb[i * 3 + c] = (byte)(255f * v);
                    }
                }
            }

            return rgb;
        }

        private static void Write(string dir, string name, byte[] rgb)
        {
            Png.Write(Path.Combine(dir, name), Pixels, Pixels, rgb);
            Console.WriteLine("wrote " + Path.Combine(dir, name));
        }

        /// <summary>数字で確かめる（絵を見るだけにしない）。</summary>
        private static void Measure(StringBuilder log)
        {
            float worst = float.MaxValue;
            int worstAt = -1;
            for (int i = 0; i < VortexPuffLayout.PuffCount; i++)
            {
                float c = VortexPuffLayout.EyeClearanceOf(i);
                if (c < worst) { worst = c; worstAt = i; }
            }

            log.AppendLine("## the eye stays a hole");
            log.AppendLine("  eye radius            = " + F(VortexPuffLayout.EyeFraction * Radius)
                           + " m (" + F2(VortexPuffLayout.EyeFraction) + " R)");
            log.AppendLine("  eyewall column radius = "
                           + F(VortexPuffLayout.EyeWallFraction * Radius)
                           + " m (" + F2(VortexPuffLayout.EyeWallFraction) + " R)");
            log.AppendLine("  tightest puff         = #" + worstAt + ", clears the eye rim by "
                           + F(worst * Radius) + " m");
            log.AppendLine();

            log.AppendLine("## layers");
            log.AppendLine("  layer   size m  disc m   band m   life s     colour bright -> dark");
            for (int i = 0; i < 3; i++)
            {
                var layer = (VortexCloudLayer)i;
                VortexCloudProfile p = VortexCloudProfile.Of(layer);
                float size = Radius * p.SizeFraction;
                if (size < Vortex.MinSizeMetres) size = Vortex.MinSizeMetres;
                if (size > Vortex.MaxSizeMetres) size = Vortex.MaxSizeMetres;

                float disc = 0f;
                float band = 0f;
                for (int k = 0; k < VortexPuffLayout.PuffCount; k++)
                {
                    VortexPuff puff = VortexPuffLayout.PuffAt(k);
                    if (puff.Layer != layer) continue;
                    if (puff.DiscFraction * Radius > disc) disc = puff.DiscFraction * Radius;
                    if (puff.BandFraction * Vortex.ThicknessMetres > band)
                        band = puff.BandFraction * Vortex.ThicknessMetres;
                }

                log.AppendLine("  " + layer.ToString().PadRight(8)
                               + F(size).PadLeft(5) + "   " + F(disc).PadLeft(5)
                               + "   " + F(band).PadLeft(5)
                               + "   " + F(p.LifeMinSeconds) + "-" + F(p.LifeMaxSeconds)
                               + "     (" + F2(p.BrightRed) + "," + F2(p.BrightGreen) + ","
                               + F2(p.BrightBlue) + ") -> (" + F2(p.DarkRed) + ","
                               + F2(p.DarkGreen) + "," + F2(p.DarkBlue) + ")");
            }
            log.AppendLine();

            log.AppendLine("## column heights (top of the canopy band, metres above cloud base)");
            for (int column = 0; column < VortexPuffLayout.ColumnCount; column++)
            {
                VortexPuff canopy = VortexPuffLayout.PuffAt(
                    column * VortexPuffLayout.LevelsPerColumn + 3);
                VortexPuff deck = VortexPuffLayout.PuffAt(
                    column * VortexPuffLayout.LevelsPerColumn);
                string kind = column < VortexPuffLayout.EyeWallColumns ? "eyewall" : "arm    ";
                log.AppendLine("  " + kind + " #" + column.ToString().PadLeft(2)
                               + "  r=" + F(canopy.RadiusFraction * Radius).PadLeft(6)
                               + " m  base=" + F(deck.HeightFraction * Vortex.ThicknessMetres)
                                   .PadLeft(5)
                               + " m  top=" + F((canopy.HeightFraction + canopy.BandFraction)
                                                * Vortex.ThicknessMetres).PadLeft(5) + " m");
            }
            log.AppendLine();
        }

        // ── 3 つの視点 ─────────────────────────────────────────

        /// <summary>真上から（平面図）。腕・壁雲・眼の穴を見る。</summary>
        private static byte[] Plan(Speck[] specks)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];
            float scale = Pixels * Fill * 0.5f / Radius;
            float half = Pixels * 0.5f;

            // 上から見るので、高いものが手前 ＝ 後ろから描く。
            Sort(specks, true);

            for (int i = 0; i < specks.Length; i++)
            {
                Speck s = specks[i];
                Splat(cover, colour, half + s.X * scale, half + s.Z * scale,
                      s.SizeMetres * 0.5f * scale, s);
            }

            return Compose(cover, colour, false);
        }

        /// <summary>
        /// 真横から（立面図）。雲底の平らさと塔の高さを見る。
        /// <paramref name="zoom"/> が 1 なら渦ぜんぶ、大きいほど眼のまわりに寄る。
        /// **縦横は同じ尺度である**（高さを誇張しない）。
        /// </summary>
        private static byte[] Elevation(Speck[] specks, float zoom)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];

            // 横から見るときも尺度は縦横同じ（高さを誇張しない）。
            float scale = Pixels * Fill * 0.5f / Radius * zoom;
            float half = Pixels * 0.5f;
            float groundY = Pixels * 0.94f;

            // 奥（+Z）から手前（-Z）へ。
            SortByZ(specks);

            for (int i = 0; i < specks.Length; i++)
            {
                Speck s = specks[i];
                Splat(cover, colour, half + s.X * scale, groundY - s.Y * scale,
                      s.SizeMetres * 0.5f * scale, s);
            }

            return Compose(cover, colour, true);
        }

        /// <summary>俯角 35 度（ゲームのカメラに近い）。**実機の見え方はこれである。**</summary>
        private static byte[] Oblique(Speck[] specks)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];

            double pitch = ObliquePitchDegrees * Math.PI / 180.0;
            float cp = (float)Math.Cos(pitch);
            float sp = (float)Math.Sin(pitch);

            float scale = Pixels * Fill * 0.5f / Radius;
            float half = Pixels * 0.5f;
            float centreY = Pixels * 0.62f;

            // 奥行き = Z·cos + Y·sin。遠いものから描く。
            Array.Sort(specks, delegate (Speck a, Speck b)
            {
                float da = a.Z * cp + a.Y * sp;
                float db = b.Z * cp + b.Y * sp;
                return db.CompareTo(da);
            });

            for (int i = 0; i < specks.Length; i++)
            {
                Speck s = specks[i];
                float sx = half + s.X * scale;
                float sy = centreY - (s.Y * cp - s.Z * sp) * scale;
                Splat(cover, colour, sx, sy, s.SizeMetres * 0.5f * scale, s);
            }

            return Compose(cover, colour, false);
        }

        /// <summary>
        /// 吹き付ける雨を真横から。**風は +X 向き**なので、粒が右へ流れて落ちていれば
        /// 「横殴り」になっている。縦横は同じ尺度である。
        /// </summary>
        private static byte[] SquallElevation(Speck[] specks)
        {
            var cover = new float[Pixels * Pixels];
            var colour = new float[Pixels * Pixels * 3];

            // 窓は幅 1400 m。地面は下から 6% のところ。
            const float windowMetres = 900f;
            float scale = Pixels / windowMetres;
            float half = Pixels * 0.5f;
            float groundY = Pixels * 0.94f;

            Array.Sort(specks, delegate (Speck a, Speck b) { return b.Z.CompareTo(a.Z); });

            for (int i = 0; i < specks.Length; i++)
            {
                Speck s = specks[i];
                Splat(cover, colour, half + s.X * scale, groundY - s.Y * scale,
                      s.SizeMetres * 0.5f * scale, s);
            }

            return Compose(cover, colour, true);
        }

        // ── 描画の下請け ────────────────────────────────────────

        private static void Sort(Speck[] specks, bool byHeight)
        {
            Array.Sort(specks, delegate (Speck a, Speck b)
            {
                return byHeight ? a.Y.CompareTo(b.Y) : a.Z.CompareTo(b.Z);
            });
        }

        private static void SortByZ(Speck[] specks)
        {
            Array.Sort(specks, delegate (Speck a, Speck b) { return b.Z.CompareTo(a.Z); });
        }

        /// <summary>柔らかい円を 1 個積む（<c>tools/VolcanoPreview</c> の Plume と同じ形）。</summary>
        private static void Splat(float[] cover, float[] colour,
                                  float cx, float cy, float radius, Speck s)
        {
            if (radius < 0.6f) radius = 0.6f;

            int x0 = (int)(cx - radius), x1 = (int)(cx + radius) + 1;
            int y0 = (int)(cy - radius), y1 = (int)(cy + radius) + 1;
            if (x1 < 0 || y1 < 0 || x0 >= Pixels || y0 >= Pixels) return;
            if (x0 < 0) x0 = 0;
            if (y0 < 0) y0 = 0;
            if (x1 > Pixels) x1 = Pixels;
            if (y1 > Pixels) y1 = Pixels;

            float r2 = radius * radius;
            float peak = SplatAlpha * s.Alpha;

            for (int y = y0; y < y1; y++)
            {
                float dy = y - cy;
                for (int x = x0; x < x1; x++)
                {
                    float dx = x - cx;
                    float d2 = dx * dx + dy * dy;
                    if (d2 >= r2) continue;

                    float fall = 1f - d2 / r2;
                    float a = peak * fall * fall;

                    int c = y * Pixels + x;
                    cover[c] += a;
                    colour[c * 3] += a * s.R;
                    colour[c * 3 + 1] += a * s.G;
                    colour[c * 3 + 2] += a * s.B;
                }
            }
        }

        private static byte[] Compose(float[] cover, float[] colour, bool withGround)
        {
            var rgb = new byte[Pixels * Pixels * 3];
            int groundRow = (int)(Pixels * 0.94f);

            for (int y = 0; y < Pixels; y++)
            {
                for (int x = 0; x < Pixels; x++)
                {
                    float r = Sky[0], g = Sky[1], b = Sky[2];
                    if (withGround && y >= groundRow)
                    {
                        r = Ground[0]; g = Ground[1]; b = Ground[2];
                    }

                    int c = y * Pixels + x;
                    float a = cover[c];
                    if (a > 0f)
                    {
                        float k = a > 1f ? 1f : a;
                        float pr = colour[c * 3] / a;
                        float pg = colour[c * 3 + 1] / a;
                        float pb = colour[c * 3 + 2] / a;
                        r = r + (pr - r) * k;
                        g = g + (pg - g) * k;
                        b = b + (pb - b) * k;
                    }

                    int o = c * 3;
                    rgb[o] = Byte(r); rgb[o + 1] = Byte(g); rgb[o + 2] = Byte(b);
                }
            }

            return rgb;
        }

        private static byte Byte(float v)
        {
            int i = (int)(v * 255f + 0.5f);
            return (byte)(i < 0 ? 0 : (i > 255 ? 255 : i));
        }

        private static string F(double v) { return v.ToString("F0", CultureInfo.InvariantCulture); }

        private static string F2(double v)
        {
            return v.ToString("F2", CultureInfo.InvariantCulture);
        }
    }
}
