using System;
using System.Globalization;
using System.IO;
using System.Text;
using DisasterPlus.Core.Common;
using DisasterPlus.Core.Earthquake;
using DisasterPlus.Tools;

namespace DisasterPlus.Tools.WaveformPreview
{
    /// <summary>
    /// バニラの揺れの式（<see cref="ShakeWaveform"/>）と合成記象
    /// （<see cref="SeismogramModel"/>）を**ゲームを起動せずに**描いて確かめる。
    ///
    /// 「見た目の変更は自分でオフラインに描画・計測してから実機テストを頼む」という
    /// このプロジェクトの決まりのための道具である。Core の実物をそのままコンパイルして
    /// 呼ぶので、**書き直した近似ではない**。パネルの絵も
    /// <see cref="WaveformPlot"/> と同じ列計算・同じ画素サイズで描く。
    ///
    ///   dotnet run --project tools/WaveformPreview -- docs/images/earthquake
    /// </summary>
    internal static class Program
    {
        /// <summary>
        /// 揺れの窓（フレーム）。<c>EarthquakeAI</c> のフィールド初期化子の実測値
        /// （IL 事実文書 §A-0a、<c>m_activeDuration = 1024</c>）。
        /// プレハブが上書きしうるので、実機の値がこれと違うことはありうる。
        /// </summary>
        private const uint Window = 1024u;

        /// <summary>震源からの距離（m）。CS のマップは一辺 17,280 m。</summary>
        private static readonly float[] Distances = { 500f, 2000f, 5000f, 10000f };

        /// <summary>地震 3 つぶんの種。**同じ距離でも形が違う**ことを見るためにある。</summary>
        private static readonly uint[] Seeds =
        {
            DeterministicRandom.Hash(11u, 900000u),
            DeterministicRandom.Hash(12u, 900500u),
            DeterministicRandom.Hash(13u, 901000u),
        };

        private static int Main(string[] args)
        {
            string outDir = args.Length > 0 ? args[0] : "docs/images/earthquake";
            Directory.CreateDirectory(outDir);

            var log = new StringBuilder();
            log.AppendLine("# Earthquake waveform preview (generated by tools/WaveformPreview)");
            log.AppendLine();
            log.AppendLine("window (m_activeDuration) = " + Window + " frames"
                           + "   [EarthquakeAI field initialiser, IL facts A-0a]");
            log.AppendLine("1 in-game minute = 45.51 sim frames (DAYTIME_FRAMES 65536 / 1440)");
            log.AppendLine();

            Traces(outDir, log);
            PanelPixels(outDir, log);
            Aliasing(outDir, log);
            BandLimit(log);
            Clipping(log);

            File.WriteAllText(Path.Combine(outDir, "waveform-measurements.txt"), log.ToString());
            Console.Write(log.ToString());
            return 0;
        }

        // ── 1. 距離ごとの記象（バニラと合成を上下に並べる） ──────────────────

        private static void Traces(string dir, StringBuilder log)
        {
            const int rowHeight = 150;
            const int gap = 6;
            int width = (int)Window;
            int height = Distances.Length * (rowHeight * 2 + gap * 2);

            var rgb = new byte[width * height * 3];
            Fill(rgb, 16, 18, 24);

            var model = SeismogramModel.For(Seeds[0], Window);

            log.AppendLine("## arrivals (seed 0)");
            log.AppendLine("  distance m | P frames | S frames | S-P frames | S-P in-game s"
                           + " | vanilla peak | model peak");

            int top = 0;
            foreach (float d in Distances)
            {
                float tP = model.PArrivalFrames(d);
                float tS = model.SArrivalFrames(d);

                float vanillaPeak = 0f, modelPeak = 0f;
                for (int f = 1; f < Window; f++)
                {
                    vanillaPeak = Math.Max(vanillaPeak, Math.Abs(ShakeWaveform.DisplacementAt(d, f)));
                    modelPeak = Math.Max(modelPeak, Math.Abs(model.DisplacementAt(d, f)));
                }

                log.AppendLine("  " + Pad(d, 10) + " | " + Pad(tP, 8) + " | " + Pad(tS, 8)
                               + " | " + Pad(tS - tP, 10) + " | " + Pad((tS - tP) / 45.51f, 13)
                               + " | " + Pad(vanillaPeak, 12) + " | " + Pad(modelPeak, 10));

                DrawRow(rgb, width, top, rowHeight, d, model, false, tP, tS);
                DrawRow(rgb, width, top + rowHeight + gap, rowHeight, d, model, true, tP, tS);
                top += rowHeight * 2 + gap * 2;
            }

            log.AppendLine();
            Png.Write(Path.Combine(dir, "waveform-model-traces.png"), width, height, rgb);
        }

        /// <summary>1 本ぶんの帯。上段がバニラ（白）、下段が合成記象（橙）。</summary>
        private static void DrawRow(byte[] rgb, int width, int top, int height, float distance,
                                    SeismogramModel model, bool synthesized, float tP, float tS)
        {
            int middle = top + height / 2;

            // 中央線と、満目盛り（±0.60）の位置。
            for (int x = 0; x < width; x++) Set(rgb, width, x, middle, 70, 76, 90);

            // P / S の到達に縦線を引く。**これが見えないなら距離の効きが出ていない。**
            VerticalLine(rgb, width, (int)tP, top, top + height, 80, 200, 220);
            VerticalLine(rgb, width, (int)tS, top, top + height, 210, 90, 200);

            float scale = (height / 2f) / ShakeWaveform.MaxDisplacement;
            for (int f = 1; f < width; f++)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);

                int row = middle - (int)Math.Round(v * scale);
                int lo = Math.Min(row, middle);
                int hi = Math.Max(row, middle);
                for (int r = lo; r <= hi; r++)
                {
                    if (synthesized) Set(rgb, width, f, r, 255, 158, 66);
                    else Set(rgb, width, f, r, 235, 235, 235);
                }
            }
        }

        // ── 2. パネルに出る画素そのもの ────────────────────────────────

        /// <summary>
        /// ゲームの <c>WaveformView</c> と**同じ 320x80 の格子・同じ列計算**で描く。
        /// 4 倍に拡大して並べる（拡大は最後だけ。格子はゲームのまま）。
        /// </summary>
        private static void PanelPixels(string dir, StringBuilder log)
        {
            const int pw = 320;
            const int ph = 80;
            const int zoom = 3;
            const int gap = 8;

            int rows = Distances.Length;
            int width = pw * zoom;
            int height = rows * (ph * zoom + gap);
            var rgb = new byte[width * height * 3];
            Fill(rgb, 30, 32, 38);

            var model = SeismogramModel.For(Seeds[0], Window);

            // 窓は「最新サンプルまでの 512 フレーム」。ゲームと同じ幅にする。
            const int plotWindow = 512;
            const uint newest = 900000u + plotWindow;      // e = 512 の瞬間を切り取る
            const uint origin = 900000u;                   // e = 0 のフレーム

            log.AppendLine("## panel pixels (320x80, e = 0..512, the game's own column maths)");

            var frames = new uint[plotWindow];
            var vanilla = new float[plotWindow];
            var synth = new float[plotWindow];

            for (int r = 0; r < rows; r++)
            {
                float d = Distances[r];
                float peak = 0f;
                for (int i = 0; i < plotWindow; i++)
                {
                    int e = i + 1;
                    frames[i] = origin + (uint)e;
                    vanilla[i] = ShakeWaveform.DisplacementAt(d, e);
                    synth[i] = model.DisplacementAt(d, e);
                    peak = Math.Max(peak, Math.Max(Math.Abs(vanilla[i]), Math.Abs(synth[i])));
                }
                float scale = peak > 0f ? 1f / peak : 1f;

                // ★ ゲームと同じ 2 段組（上段 = バニラ、下段 = 合成記象、尺度は共通）。
                int lane = ph / 2;
                int[] vanillaColumns = WaveformPlot.Columns(frames, vanilla, plotWindow,
                                                            newest - plotWindow, newest,
                                                            pw, lane - 1, scale);
                int[] modelColumns = WaveformPlot.Columns(frames, synth, plotWindow,
                                                          newest - plotWindow, newest,
                                                          pw, lane - 1, scale);

                int emptyModel = 0;
                for (int x = 0; x < pw; x++) if (modelColumns[x] == WaveformPlot.Empty) emptyModel++;

                log.AppendLine("  " + Pad(d, 8) + " m: shared full scale " + Pad(peak, 8)
                               + "   empty columns " + emptyModel + "/" + pw);

                int top = r * (ph * zoom + gap);
                Panel(rgb, width, top, pw, ph, zoom, modelColumns, vanillaColumns);
            }

            log.AppendLine();
            Png.Write(Path.Combine(dir, "waveform-panel.png"), width, height, rgb);
        }

        /// <summary>
        /// <c>WaveformView.Draw</c> と同じ 2 段組。上段が第 1 層（白）、下段が第 2 層（橙）。
        /// </summary>
        private static void Panel(byte[] rgb, int width, int top, int pw, int ph, int zoom,
                                  int[] modelColumns, int[] vanillaColumns)
        {
            int lane = ph / 2;
            int middle = (lane - 1) / 2;

            for (int y = 0; y < ph; y++)
            {
                for (int x = 0; x < pw; x++)
                {
                    byte r = 16, g = 18, b = 24;

                    // ★ 行番号 0 は**上端**である（WaveformView.SetPixel の doc）。
                    //   PNG も y = 0 が上端なので、ここは反転しない。反転すると
                    //   ゲームの画面と上下が逆の絵を見て確認したことになる。
                    int row = y;

                    if (row == middle || row == lane + middle) { r = 70; g = 76; b = 90; }
                    if (row == lane && (x % 4) == 0) { r = 70; g = 76; b = 90; }

                    if (Covers(vanillaColumns[x], row, middle)) { r = 255; g = 255; b = 255; }
                    if (Covers(modelColumns[x], row - lane, middle)) { r = 255; g = 158; b = 66; }

                    for (int zy = 0; zy < zoom; zy++)
                    {
                        for (int zx = 0; zx < zoom; zx++)
                        {
                            Set(rgb, width, x * zoom + zx, top + y * zoom + zy, r, g, b);
                        }
                    }
                }
            }
        }

        private static bool Covers(int column, int row, int middle)
        {
            if (column == WaveformPlot.Empty) return false;
            int lo = Math.Min(column, middle);
            int hi = Math.Max(column, middle);
            return row >= lo && row <= hi;
        }

        // ── 3. 折り返しの確認 ────────────────────────────────────

        /// <summary>
        /// **1 フレームに 1 点**（記録側が飛んだフレームを埋めた状態）と、
        /// **9 フレームに 1 点**（速度 3 で埋めなかった状態）を並べる。
        /// 後者に偽の長周期波が出ることと、埋めれば出ないことを目で確かめる。
        /// </summary>
        private static void Aliasing(string dir, StringBuilder log)
        {
            const int rowHeight = 150;
            const int gap = 6;
            const float distance = 2000f;
            int width = (int)Window;
            int height = (rowHeight + gap) * 4;

            var rgb = new byte[width * height * 3];
            Fill(rgb, 16, 18, 24);

            var model = SeismogramModel.For(Seeds[0], Window);

            AliasRow(rgb, width, 0, rowHeight, distance, model, false, 1);
            AliasRow(rgb, width, rowHeight + gap, rowHeight, distance, model, false, 9);
            AliasRow(rgb, width, (rowHeight + gap) * 2, rowHeight, distance, model, true, 1);
            AliasRow(rgb, width, (rowHeight + gap) * 3, rowHeight, distance, model, true, 9);

            log.AppendLine("## aliasing at 2000 m (rows: vanilla 1f, vanilla 9f, model 1f, model 9f)");
            log.AppendLine("  zero crossings per 1024 frames"
                           + " (a drop means the trace folded to a slower apparent wave)");
            log.AppendLine("  vanilla 1/frame : " + Crossings(distance, model, false, 1));
            log.AppendLine("  vanilla 1/9frame: " + Crossings(distance, model, false, 9));
            log.AppendLine("  model   1/frame : " + Crossings(distance, model, true, 1));
            log.AppendLine("  model   1/9frame: " + Crossings(distance, model, true, 9));
            log.AppendLine();

            Png.Write(Path.Combine(dir, "waveform-aliasing.png"), width, height, rgb);
        }

        private static void AliasRow(byte[] rgb, int width, int top, int height, float distance,
                                     SeismogramModel model, bool synthesized, int step)
        {
            int middle = top + height / 2;
            for (int x = 0; x < width; x++) Set(rgb, width, x, middle, 70, 76, 90);

            float scale = (height / 2f) / ShakeWaveform.MaxDisplacement;

            int previousX = -1;
            int previousRow = middle;
            for (int f = 1; f < width; f += step)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);
                int row = middle - (int)Math.Round(v * scale);

                if (previousX >= 0) Line(rgb, width, previousX, previousRow, f, row,
                                         synthesized ? (byte)255 : (byte)235,
                                         synthesized ? (byte)158 : (byte)235,
                                         synthesized ? (byte)66 : (byte)235);
                previousX = f;
                previousRow = row;
            }
        }

        private static int Crossings(float distance, SeismogramModel model, bool synthesized, int step)
        {
            int count = 0;
            float previous = 0f;
            bool has = false;
            for (int f = 1; f < Window; f += step)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);
                if (has && ((previous < 0f && v > 0f) || (previous > 0f && v < 0f))) count++;
                previous = v;
                has = true;
            }
            return count;
        }

        // ── 4. 帯域の確認（数値だけ） ──────────────────────────────

        /// <summary>
        /// **1 フレーム刻みで標本化定理を満たしているか。** 隣り合うサンプルの
        /// 位相差が π を超えると折り返す。ここで見るのは、各成分の
        /// rad/frame が π 未満であること（1 周期あたり何点取れているか）。
        /// </summary>
        private static void BandLimit(StringBuilder log)
        {
            log.AppendLine("## band limit (sampling is 1 point per sim frame -> Nyquist = pi rad/frame)");
            log.AppendLine("  vanilla fast  0.63 rad/frame -> period "
                           + Pad(6.2831853f / ShakeWaveform.FastRate, 8) + " frames");
            log.AppendLine("  model P (max) "
                           + Pad(SeismogramModel.BasePRate * 1.08f, 6) + " rad/frame -> period "
                           + Pad(6.2831853f / (SeismogramModel.BasePRate * 1.08f), 8) + " frames");
            log.AppendLine("  model S (max) "
                           + Pad(SeismogramModel.BaseSRate * 1.10f * 1.618f, 6)
                           + " rad/frame -> period "
                           + Pad(6.2831853f / (SeismogramModel.BaseSRate * 1.10f * 1.618f), 8)
                           + " frames");
            log.AppendLine("  wobble segment " + SeismogramModel.NoiseSegmentFrames + " frames");
            log.AppendLine();
        }

        /// <summary>
        /// <see cref="SeismogramModel.Gain"/> の頭打ち（|shape| == 1）がどれだけ出るか。
        /// **多いと記録計が振り切れっぱなしの絵になる**ので、割合で見張る。
        /// </summary>
        private static void Clipping(StringBuilder log)
        {
            log.AppendLine("## clipping at |shape| == 1 (gain " + SeismogramModel.Gain + ")");

            int seeds = 64;
            long total = 0, clipped = 0;
            float maxShape = 0f;

            for (int s = 0; s < seeds; s++)
            {
                var m = SeismogramModel.For(DeterministicRandom.Hash((uint)s, 4242u), Window);
                foreach (float d in Distances)
                {
                    for (int f = 1; f < Window; f++)
                    {
                        float shape = Math.Abs(m.ShapeAt(d, f));
                        total++;
                        if (shape >= 0.9999f) clipped++;
                        if (shape > maxShape) maxShape = shape;
                    }
                }
            }

            log.AppendLine("  samples " + total + ", clipped " + clipped
                           + " (" + Pad(100f * clipped / total, 7) + " %)"
                           + ", max |shape| " + Pad(maxShape, 7));
            log.AppendLine();
        }

        // ── 描画の道具 ────────────────────────────────────────

        private static void Fill(byte[] rgb, byte r, byte g, byte b)
        {
            for (int i = 0; i < rgb.Length; i += 3) { rgb[i] = r; rgb[i + 1] = g; rgb[i + 2] = b; }
        }

        private static void Set(byte[] rgb, int width, int x, int y, byte r, byte g, byte b)
        {
            if (x < 0 || x >= width || y < 0) return;
            int i = (y * width + x) * 3;
            if (i < 0 || i + 2 >= rgb.Length) return;
            rgb[i] = r; rgb[i + 1] = g; rgb[i + 2] = b;
        }

        private static void VerticalLine(byte[] rgb, int width, int x, int top, int bottom,
                                         byte r, byte g, byte b)
        {
            for (int y = top; y < bottom; y += 3) Set(rgb, width, x, y, r, g, b);
        }

        private static void Line(byte[] rgb, int width, int x0, int y0, int x1, int y1,
                                 byte r, byte g, byte b)
        {
            int steps = Math.Max(Math.Abs(x1 - x0), Math.Abs(y1 - y0));
            if (steps <= 0) { Set(rgb, width, x0, y0, r, g, b); return; }
            for (int i = 0; i <= steps; i++)
            {
                int x = x0 + (x1 - x0) * i / steps;
                int y = y0 + (y1 - y0) * i / steps;
                Set(rgb, width, x, y, r, g, b);
            }
        }

        private static string Pad(float v, int width)
        {
            string s = v.ToString("F3", CultureInfo.InvariantCulture);
            return s.PadLeft(width);
        }
    }
}
