using System;
using System.Globalization;
using System.IO;
using System.Text;
using DisasterPlus.Core.Common;
using DisasterPlus.Core.Earthquake;
using DisasterPlus.Core.Volcano;
using DisasterPlus.Tools;

namespace DisasterPlus.Tools.WaveformPreview
{
    /// <summary>
    /// Draws and checks vanilla's shake formula (<see cref="ShakeWaveform"/>) and the
    /// synthetic seismogram (<see cref="SeismogramModel"/>) **without launching the game**.
    ///
    /// This is the tool for this project's rule that "visual changes are drawn and measured
    /// offline by yourself before asking for a test in the game". It compiles and calls the
    /// real thing from Core directly, so it is **not a rewritten approximation**. The panel
    /// image is drawn with the same column maths and the same pixel size as
    /// <see cref="WaveformPlot"/>.
    ///
    ///   dotnet run --project tools/WaveformPreview -- docs/images/earthquake
    /// </summary>
    internal static class Program
    {
        /// <summary>
        /// The shake window (frames). Measured from <c>EarthquakeAI</c>'s field initialiser
        /// (the IL facts document §A-0a, <c>m_activeDuration = 1024</c>).
        /// A prefab can override it, so the value in the game may differ from this.
        /// </summary>
        private const uint Window = 1024u;

        /// <summary>Distance from the epicentre (m). A CS map is 17,280 m on a side.</summary>
        private static readonly float[] Distances = { 500f, 2000f, 5000f, 10000f };

        /// <summary>Seeds for three earthquakes. They are here to show that **the shape
        /// differs even at the same distance**.</summary>
        private static readonly uint[] Seeds =
        {
            DeterministicRandom.Hash(11u, 900000u),
            DeterministicRandom.Hash(12u, 900500u),
            DeterministicRandom.Hash(13u, 901000u),
        };

        private static int Main(string[] args)
        {
            string outDir = args.Length > 0 ? args[0] : "docs/images/earthquake";
            Directory.CreateDirectory(outDir);

            var log = new StringBuilder();
            log.AppendLine("# Earthquake waveform preview (generated by tools/WaveformPreview)");
            log.AppendLine();
            log.AppendLine("window (m_activeDuration) = " + Window + " frames"
                           + "   [EarthquakeAI field initialiser, IL facts A-0a]");
            log.AppendLine("1 in-game minute = 45.51 sim frames (DAYTIME_FRAMES 65536 / 1440)");
            log.AppendLine();

            Traces(outDir, log);
            PanelPixels(outDir, log);
            TremorPanel(outDir, log);
            Aliasing(outDir, log);
            BandLimit(log);
            Clipping(log);

            File.WriteAllText(Path.Combine(outDir, "waveform-measurements.txt"), log.ToString());
            Console.Write(log.ToString());
            return 0;
        }

        // ── 1. Seismograms per distance (vanilla above, synthetic below) ──────────────────

        private static void Traces(string dir, StringBuilder log)
        {
            const int rowHeight = 150;
            const int gap = 6;
            int width = (int)Window;
            int height = Distances.Length * (rowHeight * 2 + gap * 2);

            var rgb = new byte[width * height * 3];
            Fill(rgb, 16, 18, 24);

            var model = SeismogramModel.For(Seeds[0], Window);

            log.AppendLine("## arrivals (seed 0)");
            log.AppendLine("  distance m | P frames | S frames | S-P frames | S-P in-game s"
                           + " | vanilla peak | model peak");

            int top = 0;
            foreach (float d in Distances)
            {
                float tP = model.PArrivalFrames(d);
                float tS = model.SArrivalFrames(d);

                float vanillaPeak = 0f, modelPeak = 0f;
                for (int f = 1; f < Window; f++)
                {
                    vanillaPeak = Math.Max(vanillaPeak, Math.Abs(ShakeWaveform.DisplacementAt(d, f)));
                    modelPeak = Math.Max(modelPeak, Math.Abs(model.DisplacementAt(d, f)));
                }

                log.AppendLine("  " + Pad(d, 10) + " | " + Pad(tP, 8) + " | " + Pad(tS, 8)
                               + " | " + Pad(tS - tP, 10) + " | " + Pad((tS - tP) / 45.51f, 13)
                               + " | " + Pad(vanillaPeak, 12) + " | " + Pad(modelPeak, 10));

                DrawRow(rgb, width, top, rowHeight, d, model, false, tP, tS);
                DrawRow(rgb, width, top + rowHeight + gap, rowHeight, d, model, true, tP, tS);
                top += rowHeight * 2 + gap * 2;
            }

            log.AppendLine();
            Png.Write(Path.Combine(dir, "waveform-model-traces.png"), width, height, rgb);
        }

        /// <summary>One lane. The upper row is vanilla (white), the lower is the synthetic
        /// seismogram (orange).</summary>
        private static void DrawRow(byte[] rgb, int width, int top, int height, float distance,
                                    SeismogramModel model, bool synthesized, float tP, float tS)
        {
            int middle = top + height / 2;

            // The centre line and the position of full scale (+/-0.60).
            for (int x = 0; x < width; x++) Set(rgb, width, x, middle, 70, 76, 90);

            // Vertical lines at the P and S arrivals. **If these are not visible, the effect
            // of distance is not coming through.**
            VerticalLine(rgb, width, (int)tP, top, top + height, 80, 200, 220);
            VerticalLine(rgb, width, (int)tS, top, top + height, 210, 90, 200);

            float scale = (height / 2f) / ShakeWaveform.MaxDisplacement;
            for (int f = 1; f < width; f++)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);

                int row = middle - (int)Math.Round(v * scale);
                int lo = Math.Min(row, middle);
                int hi = Math.Max(row, middle);
                for (int r = lo; r <= hi; r++)
                {
                    if (synthesized) Set(rgb, width, f, r, 255, 158, 66);
                    else Set(rgb, width, f, r, 235, 235, 235);
                }
            }
        }

        // ── 2b. The volcanic tremor lane (the third layer) ────────────────────

        /// <summary>
        /// Draws and checks **the volcanic earthquakes recorded by the seismograph**
        /// (2026-08-22) on the same 320x80 grid as the game.
        ///
        /// The values are produced the same way as
        /// <c>Game/Volcano/VolcanoTremorTrace.DisplacementAt</c>.
        /// **The real thing from Core is called directly**, so it is not an approximate
        /// rewrite (only the gain constant lives on the Game side, so the same formula is
        /// written out here).
        /// </summary>
        private static void TremorPanel(string dir, StringBuilder log)
        {
            const int pw = 320;
            const int ph = 80;
            const int zoom = 3;
            const int gap = 8;
            const int plotWindow = 512;

            // Mountain radius 1200 m -> the reach is 4.5 times that = 5400 m.
            const float reach = 1200f * 4.5f;
            const float gain = 0.7f * ShakeWaveform.MaxDisplacement;
            float[] distances = { 300f, 1500f, 4000f };
            float[] activities = { 0.62f, 1.00f };

            uint seed = DeterministicRandom.Hash(88u, 4294966898u);

            int rows = distances.Length * activities.Length;
            int width = pw * zoom;
            int height = rows * (ph * zoom + gap);
            var rgb = new byte[width * height * 3];
            Fill(rgb, 30, 32, 38);

            log.AppendLine("## volcanic tremor panel (320x80, 512 frames = 8.53 s at speed 1)");
            log.AppendLine("  reach = " + reach + " m   gain = " + gain);
            log.AppendLine("  distance m | activity | attenuation | peak | empty columns");

            var frames = new uint[plotWindow];
            var values = new float[plotWindow];
            int row = 0;

            foreach (float a in activities)
            {
                foreach (float d in distances)
                {
                    float attenuation = VolcanicTremor.AttenuationAt(d, reach);
                    float peak = 0f;
                    for (int i = 0; i < plotWindow; i++)
                    {
                        frames[i] = (uint)i;
                        values[i] = VolcanicTremor.DisplacementAt(seed, i / 60f, a)
                                    * attenuation * gain;
                        peak = Math.Max(peak, Math.Abs(values[i]));
                    }

                    float scale = peak > 0f ? 1f / peak : 1f;
                    int[] columns = WaveformPlot.Columns(frames, values, plotWindow,
                                                         0u, (uint)(plotWindow - 1),
                                                         pw, ph - 1, scale);

                    int empty = 0;
                    for (int x = 0; x < pw; x++) if (columns[x] == WaveformPlot.Empty) empty++;

                    log.AppendLine("  " + Pad(d, 10) + " | " + Pad(a, 8) + " | "
                                   + Pad(attenuation, 11) + " | " + Pad(peak, 4)
                                   + " | " + empty + "/" + pw);

                    TremorLane(rgb, width, row * (ph * zoom + gap), pw, ph, zoom, columns);
                    row++;
                }
            }

            log.AppendLine();
            Png.Write(Path.Combine(dir, "waveform-tremor-panel.png"), width, height, rgb);
        }

        /// <summary>A single lane. The colour is the same as
        /// <c>WaveformView.TremorColor</c> (blue-green).</summary>
        private static void TremorLane(byte[] rgb, int width, int top, int pw, int ph, int zoom,
                                       int[] columns)
        {
            int middle = (ph - 1) / 2;
            for (int x = 0; x < pw; x++)
            {
                Block(rgb, width, x, middle, top, zoom, 70, 76, 90);

                int v = columns[x];
                if (v == WaveformPlot.Empty) continue;

                int lo = Math.Min(v, middle);
                int hi = Math.Max(v, middle);
                for (int y = lo; y <= hi; y++) Block(rgb, width, x, y, top, zoom, 96, 220, 200);
            }
        }

        private static void Block(byte[] rgb, int width, int x, int y, int top, int zoom,
                                  byte r, byte g, byte b)
        {
            for (int dy = 0; dy < zoom; dy++)
            {
                for (int dx = 0; dx < zoom; dx++)
                {
                    Set(rgb, width, x * zoom + dx, top + y * zoom + dy, r, g, b);
                }
            }
        }

        // ── 2. The actual pixels that appear on the panel ────────────────────────────────

        /// <summary>
        /// Drawn on **the same 320x80 grid with the same column maths** as the game's
        /// <c>WaveformView</c>. Laid out at 4x magnification (the magnification happens last
        /// only; the grid stays exactly as in the game).
        /// </summary>
        private static void PanelPixels(string dir, StringBuilder log)
        {
            const int pw = 320;
            const int ph = 80;
            const int zoom = 3;
            const int gap = 8;

            int rows = Distances.Length;
            int width = pw * zoom;
            int height = rows * (ph * zoom + gap);
            var rgb = new byte[width * height * 3];
            Fill(rgb, 30, 32, 38);

            var model = SeismogramModel.For(Seeds[0], Window);

            // The window is "the 512 frames up to the newest sample". Same width as the game.
            const int plotWindow = 512;
            const uint newest = 900000u + plotWindow;      // take the snapshot at e = 512
            const uint origin = 900000u;                   // the frame where e = 0

            log.AppendLine("## panel pixels (320x80, e = 0..512, the game's own column maths)");

            var frames = new uint[plotWindow];
            var vanilla = new float[plotWindow];
            var synth = new float[plotWindow];

            for (int r = 0; r < rows; r++)
            {
                float d = Distances[r];
                float peak = 0f;
                for (int i = 0; i < plotWindow; i++)
                {
                    int e = i + 1;
                    frames[i] = origin + (uint)e;
                    vanilla[i] = ShakeWaveform.DisplacementAt(d, e);
                    synth[i] = model.DisplacementAt(d, e);
                    peak = Math.Max(peak, Math.Max(Math.Abs(vanilla[i]), Math.Abs(synth[i])));
                }
                float scale = peak > 0f ? 1f / peak : 1f;

                // ★ The same two-lane layout as the game (upper = vanilla, lower = the
                //   synthetic seismogram, on a shared scale).
                int lane = ph / 2;
                int[] vanillaColumns = WaveformPlot.Columns(frames, vanilla, plotWindow,
                                                            newest - plotWindow, newest,
                                                            pw, lane - 1, scale);
                int[] modelColumns = WaveformPlot.Columns(frames, synth, plotWindow,
                                                          newest - plotWindow, newest,
                                                          pw, lane - 1, scale);

                int emptyModel = 0;
                for (int x = 0; x < pw; x++) if (modelColumns[x] == WaveformPlot.Empty) emptyModel++;

                log.AppendLine("  " + Pad(d, 8) + " m: shared full scale " + Pad(peak, 8)
                               + "   empty columns " + emptyModel + "/" + pw);

                int top = r * (ph * zoom + gap);
                Panel(rgb, width, top, pw, ph, zoom, modelColumns, vanillaColumns);
            }

            log.AppendLine();
            Png.Write(Path.Combine(dir, "waveform-panel.png"), width, height, rgb);
        }

        /// <summary>
        /// The same two-lane layout as <c>WaveformView.Draw</c>. The upper lane is layer 1
        /// (white), the lower is layer 2 (orange).
        /// </summary>
        private static void Panel(byte[] rgb, int width, int top, int pw, int ph, int zoom,
                                  int[] modelColumns, int[] vanillaColumns)
        {
            int lane = ph / 2;
            int middle = (lane - 1) / 2;

            for (int y = 0; y < ph; y++)
            {
                for (int x = 0; x < pw; x++)
                {
                    byte r = 16, g = 18, b = 24;

                    // ★ Row 0 is **the top edge** (see the doc of WaveformView.SetPixel).
                    //   In PNG too, y = 0 is the top edge, so nothing is flipped here. Flip it
                    //   and you would be checking a picture that is upside down relative to
                    //   the game's screen.
                    int row = y;

                    if (row == middle || row == lane + middle) { r = 70; g = 76; b = 90; }
                    if (row == lane && (x % 4) == 0) { r = 70; g = 76; b = 90; }

                    if (Covers(vanillaColumns[x], row, middle)) { r = 255; g = 255; b = 255; }
                    if (Covers(modelColumns[x], row - lane, middle)) { r = 255; g = 158; b = 66; }

                    for (int zy = 0; zy < zoom; zy++)
                    {
                        for (int zx = 0; zx < zoom; zx++)
                        {
                            Set(rgb, width, x * zoom + zx, top + y * zoom + zy, r, g, b);
                        }
                    }
                }
            }
        }

        private static bool Covers(int column, int row, int middle)
        {
            if (column == WaveformPlot.Empty) return false;
            int lo = Math.Min(column, middle);
            int hi = Math.Max(column, middle);
            return row >= lo && row <= hi;
        }

        // ── 3. Checking for aliasing ────────────────────────────────────

        /// <summary>
        /// Lays out **one point per frame** (the recorder having filled in the frames it
        /// skipped) alongside **one point every 9 frames** (at speed 3 without filling in).
        /// Confirms by eye that the latter produces a spurious long-period wave, and that
        /// filling in removes it.
        /// </summary>
        private static void Aliasing(string dir, StringBuilder log)
        {
            const int rowHeight = 150;
            const int gap = 6;
            const float distance = 2000f;
            int width = (int)Window;
            int height = (rowHeight + gap) * 4;

            var rgb = new byte[width * height * 3];
            Fill(rgb, 16, 18, 24);

            var model = SeismogramModel.For(Seeds[0], Window);

            AliasRow(rgb, width, 0, rowHeight, distance, model, false, 1);
            AliasRow(rgb, width, rowHeight + gap, rowHeight, distance, model, false, 9);
            AliasRow(rgb, width, (rowHeight + gap) * 2, rowHeight, distance, model, true, 1);
            AliasRow(rgb, width, (rowHeight + gap) * 3, rowHeight, distance, model, true, 9);

            log.AppendLine("## aliasing at 2000 m (rows: vanilla 1f, vanilla 9f, model 1f, model 9f)");
            log.AppendLine("  zero crossings per 1024 frames"
                           + " (a drop means the trace folded to a slower apparent wave)");
            log.AppendLine("  vanilla 1/frame : " + Crossings(distance, model, false, 1));
            log.AppendLine("  vanilla 1/9frame: " + Crossings(distance, model, false, 9));
            log.AppendLine("  model   1/frame : " + Crossings(distance, model, true, 1));
            log.AppendLine("  model   1/9frame: " + Crossings(distance, model, true, 9));
            log.AppendLine();

            Png.Write(Path.Combine(dir, "waveform-aliasing.png"), width, height, rgb);
        }

        private static void AliasRow(byte[] rgb, int width, int top, int height, float distance,
                                     SeismogramModel model, bool synthesized, int step)
        {
            int middle = top + height / 2;
            for (int x = 0; x < width; x++) Set(rgb, width, x, middle, 70, 76, 90);

            float scale = (height / 2f) / ShakeWaveform.MaxDisplacement;

            int previousX = -1;
            int previousRow = middle;
            for (int f = 1; f < width; f += step)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);
                int row = middle - (int)Math.Round(v * scale);

                if (previousX >= 0) Line(rgb, width, previousX, previousRow, f, row,
                                         synthesized ? (byte)255 : (byte)235,
                                         synthesized ? (byte)158 : (byte)235,
                                         synthesized ? (byte)66 : (byte)235);
                previousX = f;
                previousRow = row;
            }
        }

        private static int Crossings(float distance, SeismogramModel model, bool synthesized, int step)
        {
            int count = 0;
            float previous = 0f;
            bool has = false;
            for (int f = 1; f < Window; f += step)
            {
                float v = synthesized
                    ? model.DisplacementAt(distance, f)
                    : ShakeWaveform.DisplacementAt(distance, f);
                if (has && ((previous < 0f && v > 0f) || (previous > 0f && v < 0f))) count++;
                previous = v;
                has = true;
            }
            return count;
        }

        // ── 4. Checking the band limit (numbers only) ──────────────────────────────

        /// <summary>
        /// **Is the sampling theorem satisfied at one sample per frame?** If the phase
        /// difference between adjacent samples exceeds π, it aliases. What is checked here is
        /// that each component's rad/frame is below π (i.e. how many points are taken per
        /// cycle).
        /// </summary>
        private static void BandLimit(StringBuilder log)
        {
            log.AppendLine("## band limit (sampling is 1 point per sim frame -> Nyquist = pi rad/frame)");
            log.AppendLine("  vanilla fast  0.63 rad/frame -> period "
                           + Pad(6.2831853f / ShakeWaveform.FastRate, 8) + " frames");
            log.AppendLine("  model P (max) "
                           + Pad(SeismogramModel.BasePRate * 1.08f, 6) + " rad/frame -> period "
                           + Pad(6.2831853f / (SeismogramModel.BasePRate * 1.08f), 8) + " frames");
            log.AppendLine("  model S (max) "
                           + Pad(SeismogramModel.BaseSRate * 1.10f * 1.618f, 6)
                           + " rad/frame -> period "
                           + Pad(6.2831853f / (SeismogramModel.BaseSRate * 1.10f * 1.618f), 8)
                           + " frames");
            log.AppendLine("  wobble segment " + SeismogramModel.NoiseSegmentFrames + " frames");
            log.AppendLine();
        }

        /// <summary>
        /// How often <see cref="SeismogramModel.Gain"/> hits its ceiling (|shape| == 1).
        /// **Too often and the picture is just a recorder pinned at full deflection**, so the
        /// proportion is watched.
        /// </summary>
        private static void Clipping(StringBuilder log)
        {
            log.AppendLine("## clipping at |shape| == 1 (gain " + SeismogramModel.Gain + ")");

            int seeds = 64;
            long total = 0, clipped = 0;
            float maxShape = 0f;

            for (int s = 0; s < seeds; s++)
            {
                var m = SeismogramModel.For(DeterministicRandom.Hash((uint)s, 4242u), Window);
                foreach (float d in Distances)
                {
                    for (int f = 1; f < Window; f++)
                    {
                        float shape = Math.Abs(m.ShapeAt(d, f));
                        total++;
                        if (shape >= 0.9999f) clipped++;
                        if (shape > maxShape) maxShape = shape;
                    }
                }
            }

            log.AppendLine("  samples " + total + ", clipped " + clipped
                           + " (" + Pad(100f * clipped / total, 7) + " %)"
                           + ", max |shape| " + Pad(maxShape, 7));
            log.AppendLine();
        }

        // ── Drawing helpers ────────────────────────────────────────

        private static void Fill(byte[] rgb, byte r, byte g, byte b)
        {
            for (int i = 0; i < rgb.Length; i += 3) { rgb[i] = r; rgb[i + 1] = g; rgb[i + 2] = b; }
        }

        private static void Set(byte[] rgb, int width, int x, int y, byte r, byte g, byte b)
        {
            if (x < 0 || x >= width || y < 0) return;
            int i = (y * width + x) * 3;
            if (i < 0 || i + 2 >= rgb.Length) return;
            rgb[i] = r; rgb[i + 1] = g; rgb[i + 2] = b;
        }

        private static void VerticalLine(byte[] rgb, int width, int x, int top, int bottom,
                                         byte r, byte g, byte b)
        {
            for (int y = top; y < bottom; y += 3) Set(rgb, width, x, y, r, g, b);
        }

        private static void Line(byte[] rgb, int width, int x0, int y0, int x1, int y1,
                                 byte r, byte g, byte b)
        {
            int steps = Math.Max(Math.Abs(x1 - x0), Math.Abs(y1 - y0));
            if (steps <= 0) { Set(rgb, width, x0, y0, r, g, b); return; }
            for (int i = 0; i <= steps; i++)
            {
                int x = x0 + (x1 - x0) * i / steps;
                int y = y0 + (y1 - y0) * i / steps;
                Set(rgb, width, x, y, r, g, b);
            }
        }

        private static string Pad(float v, int width)
        {
            string s = v.ToString("F3", CultureInfo.InvariantCulture);
            return s.PadLeft(width);
        }
    }
}
