using System;
using System.Globalization;
using System.IO;
using System.Text;
using DisasterPlus.Core.Common;
using DisasterPlus.Core.Volcano;
using DisasterPlus.Tools;

namespace DisasterPlus.Tools.VolcanoPreview
{
    /// <summary>
    /// 火山の起伏と隆起アニメーションを**ゲームを起動せずに**描いて確かめる。
    ///
    /// 「見た目の変更は自分でオフラインに描画・計測してから実機テストを頼む」という
    /// このプロジェクトの決まりのための道具である。Core の実物
    /// （<see cref="VolcanoRelief"/> / <see cref="VolcanoShape"/> / <see cref="UpliftSchedule"/>）
    /// をそのままコンパイルして呼ぶので、**書き直した近似ではない**。
    ///
    ///   dotnet run --project tools/VolcanoPreview -- docs/images/volcano
    /// </summary>
    internal static class Program
    {
        /// <summary>raw セルの一辺（m）。ゲームの地形格子そのもの。</summary>
        private const float Cell = VolcanoShape.RawCellSizeMetres;

        /// <summary>画像の目標の一辺（px）。倍率は整数倍にして格子を残す。</summary>
        private const int TargetPixels = 720;

        private static int ZoomFor(int cells)
        {
            int z = TargetPixels / cells;
            return z < 1 ? 1 : (z > 16 ? 16 : z);
        }

        /// <summary>山の地点から出す種（<c>VolcanoUplift</c> と同じ作り方）。</summary>
        private static readonly uint Seed = DeterministicRandom.Hash(275u, unchecked((uint)(-283)));

        private static readonly VolcanoForm[] Forms =
            { VolcanoForm.Shield, VolcanoForm.Strato, VolcanoForm.Dome };

        private static int Main(string[] args)
        {
            string outDir = args.Length > 0 ? args[0] : "docs/images/volcano";
            Directory.CreateDirectory(outDir);

            var log = new StringBuilder();
            log.AppendLine("# Volcano relief preview (generated by tools/VolcanoPreview)");
            log.AppendLine();
            log.AppendLine("seed = " + Seed + " (centre 275,-283, the playtest log's volcano)");
            log.AppendLine("grid = " + Cell.ToString(CultureInfo.InvariantCulture) + " m (the game's own terrain grid)");
            log.AppendLine();

            foreach (VolcanoForm form in Forms)
            {
                float r = VolcanoShape.DefaultRadiusOf(form);
                float h = VolcanoShape.DefaultHeightOf(form);

                Field on = Build(form, r, h, 1f);
                Field off = Build(form, r, h, 0f);

                Save(outDir, Name(form) + "-relief-1.0.png", on);
                Save(outDir, Name(form) + "-relief-0.0.png", off);
                SaveFlank(outDir, Name(form) + "-flank-1.0.png", on);

                Report(log, form, r, h, on, off);
                CrossSection(outDir, log, form, r, h, on, off);
            }

            Relief.Report(log);
            GrowthFrames(outDir, log);
            CraterFrames(outDir, log);
            Plume.Report(outDir, log);
            Lava.Report(outDir, log);
            Surge.Report(outDir, log);
            Ballistics.Report(outDir, log);
            Tremor.Report(outDir, log);
            Pacing.Report(outDir, log);

            File.WriteAllText(Path.Combine(outDir, "measurements.txt"), log.ToString());
            Console.Write(log.ToString());
            return 0;
        }

        // ── 高さ場 ──────────────────────────────────────────────

        private sealed class Field
        {
            public int Size;
            public float RadiusMetres;
            public float HeightMetres;
            public float[] H;
            public VolcanoRelief Relief;

            public float At(int x, int z) { return H[z * Size + x]; }
        }

        /// <summary>ゲームと同じ 16 m 格子で、山を覆う正方形ぶんだけ評価する。</summary>
        private static Field Build(VolcanoForm form, float radius, float height, float strength)
        {
            int half = (int)Math.Ceiling(radius / Cell) + 1;
            int size = half * 2 + 1;

            var f = new Field
            {
                Size = size,
                RadiusMetres = radius,
                HeightMetres = height,
                H = new float[size * size],
                Relief = VolcanoRelief.For(form, Seed, strength)
            };

            for (int z = 0; z < size; z++)
            {
                float dz = (z - half) * Cell;
                for (int x = 0; x < size; x++)
                {
                    float dx = (x - half) * Cell;
                    // ★ ゲームが実際に書く形そのもの（火口はプロファイルの一部である）。
                    f.H[z * size + x] = VolcanoCrater.ProfileAt(f.Relief, dx, dz, radius, height);
                }
            }
            return f;
        }

        // ── 描画 ────────────────────────────────────────────────

        /// <summary>
        /// 陰影（北西 45 度からの平行光）＋標高の色＋等高線。
        /// **16 m 格子のまま**描く（ゲームが実際に書く解像度そのもの）。
        /// 等高線を入れてあるのは、谷の刻みを目でなく数えて確かめるためである。
        /// </summary>
        private static byte[] Shade(Field f, float displayMax, float contourMetres)
        {
            int n = f.Size;
            var rgb = new byte[n * n * 3];

            for (int z = 0; z < n; z++)
            {
                for (int x = 0; x < n; x++)
                {
                    float hc = f.At(x, z);
                    float hx = f.At(Math.Min(x + 1, n - 1), z) - f.At(Math.Max(x - 1, 0), z);
                    float hz = f.At(x, Math.Min(z + 1, n - 1)) - f.At(x, Math.Max(z - 1, 0));

                    // 高さを 2 倍に誇張して法線を出す（細かい起伏を目で追えるように）。
                    const float Exaggeration = 2f;
                    float nx = -hx * Exaggeration / (2f * Cell);
                    float nz = -hz * Exaggeration / (2f * Cell);
                    float len = (float)Math.Sqrt(nx * nx + 1f + nz * nz);
                    const float lx = -0.62f, ly = 0.48f, lz = -0.62f;
                    float lambert = (nx * lx + ly + nz * lz) / len;
                    if (lambert < 0f) lambert = 0f;
                    float shade = 0.30f + 1.20f * lambert;
                    if (shade > 1.45f) shade = 1.45f;

                    float t = displayMax > 0f ? hc / displayMax : 0f;
                    if (t < 0f) t = 0f;
                    if (t > 1f) t = 1f;

                    float rr, gg, bb;
                    if (hc <= 0f) { rr = 0.42f; gg = 0.47f; bb = 0.40f; shade = 1f; }
                    else Ramp(t, out rr, out gg, out bb);

                    // 等高線: 隣のセルとのあいだで刻みをまたいだら線を引く。
                    // ★ 隣との差が刻みより大きい（＝急斜面）ところでは線を描かない ——
                    //   描くと線ではなく市松模様になる（16 m 格子では線が引けない密度）。
                    if (hc > 0f && contourMetres > 0f)
                    {
                        int c0 = (int)(hc / contourMetres);
                        float hr = f.At(Math.Min(x + 1, n - 1), z);
                        float hd = f.At(x, Math.Min(z + 1, n - 1));
                        // 線の間隔が 3 セルを割るところでは描かない（描くと市松模様になる）。
                        float sparse = contourMetres / 3f;
                        bool edge = (Math.Abs(hr - hc) < sparse && c0 != (int)(hr / contourMetres))
                                 || (Math.Abs(hd - hc) < sparse && c0 != (int)(hd / contourMetres));
                        if (edge) { rr *= 0.45f; gg *= 0.45f; bb *= 0.45f; }
                    }

                    int i = (z * n + x) * 3;
                    rgb[i] = Byte(rr * shade);
                    rgb[i + 1] = Byte(gg * shade);
                    rgb[i + 2] = Byte(bb * shade);
                }
            }
            return rgb;
        }

        /// <summary>低: 緑 → 中: 土 → 高: 岩 → 頂: 明るい灰。</summary>
        private static void Ramp(float t, out float r, out float g, out float b)
        {
            if (t < 0.35f) { float u = t / 0.35f; r = 0.30f + 0.32f * u; g = 0.52f + 0.09f * u; b = 0.24f + 0.12f * u; }
            else if (t < 0.72f) { float u = (t - 0.35f) / 0.37f; r = 0.62f - 0.10f * u; g = 0.61f - 0.22f * u; b = 0.36f - 0.05f * u; }
            else { float u = (t - 0.72f) / 0.28f; r = 0.52f + 0.42f * u; g = 0.39f + 0.48f * u; b = 0.31f + 0.50f * u; }
        }

        private static byte Byte(float v)
        {
            int i = (int)(v * 255f + 0.5f);
            return (byte)(i < 0 ? 0 : (i > 255 ? 255 : i));
        }

        /// <summary>
        /// 等高線の刻み。**16 m 格子で線が引ける密度まで粗くする** ——
        /// 細かくすると線ではなく市松模様になる（急斜面では 1 セルで刻みを跨ぐ）。
        /// </summary>
        private static float ContourFor(float h, float r)
        {
            float bySlope = 4f * Cell * (r > 0f ? h / r : 1f);
            float byHeight = h / 12f;
            return bySlope > byHeight ? bySlope : byHeight;
        }

        private static void Save(string dir, string name, Field f)
        {
            byte[] small = Shade(f, f.HeightMetres, ContourFor(f.HeightMetres, f.RadiusMetres));
            int zoom = ZoomFor(f.Size);
            byte[] big = Upscale(small, f.Size, f.Size, zoom);
            Png.Write(Path.Combine(dir, name), f.Size * zoom, f.Size * zoom, big);
            Console.WriteLine("wrote " + Path.Combine(dir, name) + "  (" + f.Size + "x" + f.Size + " cells)");
        }

        /// <summary>
        /// 山肌そのものを見るための切り出し（**北西の斜面**、等高線なし）。
        /// 北西なのは陰影の光源がそちらから来ているからで、南東を切ると影で真っ暗になる。
        /// **上からの俯瞰では等高線が細かい溝を隠す** —— 谷の刻みを目で見るための絵である。
        /// </summary>
        private static void SaveFlank(string dir, string name, Field f)
        {
            byte[] small = Shade(f, f.HeightMetres, 0f);
            int half = (f.Size - 1) / 2;
            int side = half + 1;
            if (side < 4) return;

            var crop = new byte[side * side * 3];
            for (int z = 0; z < side; z++)
            {
                for (int x = 0; x < side; x++)
                {
                    int s = (z * f.Size + x) * 3;
                    int d = (z * side + x) * 3;
                    crop[d] = small[s]; crop[d + 1] = small[s + 1]; crop[d + 2] = small[s + 2];
                }
            }

            int zoom = ZoomFor(side);
            byte[] big = Upscale(crop, side, side, zoom);
            Png.Write(Path.Combine(dir, name), side * zoom, side * zoom, big);
            Console.WriteLine("wrote " + Path.Combine(dir, name) + "  (NW flank, no contours)");
        }

        private static byte[] Upscale(byte[] src, int w, int h, int k)
        {
            var dst = new byte[w * k * h * k * 3];
            for (int y = 0; y < h * k; y++)
            {
                int sy = y / k;
                for (int x = 0; x < w * k; x++)
                {
                    int sx = x / k;
                    int s = (sy * w + sx) * 3;
                    int d = (y * w * k + x) * 3;
                    dst[d] = src[s]; dst[d + 1] = src[s + 1]; dst[d + 2] = src[s + 2];
                }
            }
            return dst;
        }

        // ── 計測 ────────────────────────────────────────────────

        private static string Name(VolcanoForm f)
        {
            return f == VolcanoForm.Shield ? "shield" : (f == VolcanoForm.Dome ? "dome" : "strato");
        }

        private static void Report(StringBuilder log, VolcanoForm form, float r, float h,
                                   Field on, Field off)
        {
            // 制約の実測: R の外はきっかり 0 / H を超えない / 強さ 0 は今日と完全一致。
            float maxOn = 0f, maxOff = 0f;
            float worstOutside = 0f;
            double diff = 0f;
            int half = (on.Size - 1) / 2;

            for (int z = 0; z < on.Size; z++)
            {
                float dz = (z - half) * Cell;
                for (int x = 0; x < on.Size; x++)
                {
                    float dx = (x - half) * Cell;
                    float d = (float)Math.Sqrt(dx * dx + dz * dz);

                    float a = on.At(x, z), b = off.At(x, z);
                    if (a > maxOn) maxOn = a;
                    if (b > maxOff) maxOff = b;
                    if (d >= r && a > worstOutside) worstOutside = a;

                    // 強さ 0 は「立て直した円錐 ∧ 火口の天井」そのものでなければならない
                    // （ここだけは VolcanoCrater を通さず、式を独立に組み直して比べる）。
                    float cone = VolcanoShape.ProfileAt(form, d, r,
                                                        h * VolcanoCrater.SummitScale(form, r));
                    float ceiling = VolcanoCrater.CeilingMetres(d, r, h);
                    float today = cone < ceiling ? cone : ceiling;
                    double e = Math.Abs(today - b);
                    if (e > diff) diff = e;
                }
            }

            var rel = on.Relief;
            log.AppendLine("## " + Name(form) + "  R=" + F(r) + " m  H=" + F(h) + " m");
            log.AppendLine("  gullies             : " + rel.GulliesText(r));
            log.AppendLine("  rills               : " + rel.RillsText(r));
            log.AppendLine("  finest wavelength   : " + F(rel.MicroWavelengthMetres) + " m ("
                           + F1(rel.MicroWavelengthMetres / Cell) + " cells)");
            log.AppendLine("  extrema density     : " + F3(ExtremaDensity(on))
                           + " / " + F3(ExtremaDensity(off))
                           + "   (relief=1 / relief=0; 0.5 = checkerboard)");
            log.AppendLine("  max height relief=1 : " + F4(maxOn) + " m   (ceiling H = " + F(h) + ")");
            log.AppendLine("  max height relief=0 : " + F4(maxOff) + " m");
            log.AppendLine("  max height beyond R : " + F4(worstOutside) + " m   (must be 0)");
            log.AppendLine("  relief=0 vs today   : max |diff| = " + diff.ToString("G3", CultureInfo.InvariantCulture)
                           + " m   (must be 0)");
        }

        /// <summary>山頂を通る断面。**傾斜と谷の深さを数字で読めるようにする。**</summary>
        private static void CrossSection(string dir, StringBuilder log, VolcanoForm form,
                                         float r, float h, Field on, Field off)
        {
            int half = (on.Size - 1) / 2;
            int samples = half + 1;

            // 東西の 1 本と、いちばん深い谷を通る 1 本。
            var eastOn = new float[samples];
            var eastOff = new float[samples];
            for (int i = 0; i < samples; i++)
            {
                eastOn[i] = on.At(half + i, half);
                eastOff[i] = off.At(half + i, half);
            }

            // 中腹（0.55R）の円周を 720 分割して、最深と最浅の方位を探す。
            float ring = 0.55f * r;
            float deep = float.MaxValue, shallow = float.MinValue;
            double deepAngle = 0, shallowAngle = 0;
            for (int a = 0; a < 720; a++)
            {
                double th = 2.0 * Math.PI * a / 720.0;
                float dx = (float)(Math.Cos(th) * ring);
                float dz = (float)(Math.Sin(th) * ring);
                float v = VolcanoCrater.ProfileAt(on.Relief, dx, dz, r, h);
                if (v < deep) { deep = v; deepAngle = th; }
                if (v > shallow) { shallow = v; shallowAngle = th; }
            }
            float smooth = VolcanoShape.ProfileAt(form, ring, r,
                                                  h * VolcanoCrater.SummitScale(form, r));

            log.AppendLine("  cross-section @0.55R = " + F(ring) + " m:");
            log.AppendLine("    smooth cone       : " + F1(smooth) + " m");
            log.AppendLine("    deepest gully     : " + F1(deep) + " m  (-" + F1(smooth - deep)
                           + " m, azimuth " + F(Deg(deepAngle)) + " deg)");
            log.AppendLine("    highest interfluve: " + F1(shallow) + " m  ("
                           + F1(shallow - smooth) + " m)");
            log.AppendLine("    ridge-to-valley   : " + F1(shallow - deep) + " m");
            RingSpread(log, on.Relief, r, h, 0.85f);
            Relief.Continuity(log, "continuity", on.Relief, form, r, h);
            Relief.Continuity(log, "continuity(off)", off.Relief, form, r, h);
            // ★★ 溝が「線」として続いているかは**本数で割った指標でしか測れない。**
            //    最初に使った「陰影を半径方向に歩いて明暗の反転を数える」指標は、
            //    対照実験（谷を 18→36 本に増やしただけの単層の山）でも同じ値を返した ——
            //    数えていたのは途切れではなく本数だった。GroovePersistence の doc 参照。
            log.AppendLine("    groove persistence (1.0 = every trough continues into the next"
                           + " 16 m ring = a solid line; master's single tier scores 0.856):");
            log.AppendLine("      relief=1  inner 0.15-0.50R "
                           + F3(GroovePersistence(on, 0.15f, 0.50f))
                           + " | outer 0.50-0.98R " + F3(GroovePersistence(on, 0.50f, 0.98f)));

            // 半径方向の傾斜（平均、度）。
            log.AppendLine("    mean slope        : " + F1(Deg(Math.Atan(h / r))) + " deg (smooth cone)");
            log.AppendLine("    footprint radius  : min " + F(MinReach(on, r, h)) + " m / max "
                           + F(MaxReach(on, r, h)) + " m  (R = " + F(r) + ")");
            log.AppendLine();

            // 断面のグラフ。上が起伏あり、薄い線が今日の滑らかな円錐。
            var gully = new float[samples];
            for (int i = 0; i < samples; i++)
            {
                float d = i * Cell;
                gully[i] = VolcanoCrater.ProfileAt(on.Relief, (float)(Math.Cos(deepAngle) * d),
                                                   (float)(Math.Sin(deepAngle) * d), r, h);
            }

            Plot(Path.Combine(dir, Name(form) + "-section.png"), h, r,
                 new[] { eastOff, eastOn, gully },
                 new[] { 0xB0B0B0, 0xE04A2F, 0x2F6BE0 });

            using (var w = new StreamWriter(Path.Combine(dir, Name(form) + "-section.csv")))
            {
                w.WriteLine("distance_m,smooth_m,relief_east_m,relief_deepest_gully_m");
                for (int i = 0; i < samples; i++)
                {
                    w.WriteLine(F(i * Cell) + "," + F2(eastOff[i]) + "," + F2(eastOn[i])
                                + "," + F2(gully[i]));
                }
            }
        }

        /// <summary>
        /// 半径 <paramref name="fraction"/>R の円周に沿った起伏の刻み。
        /// **細谷が効いているかはここでしか数字にならない**（0.55R はまだ出はじめる前）。
        /// </summary>
        private static void RingSpread(StringBuilder log, VolcanoRelief relief,
                                       float r, float h, float fraction)
        {
            float ring = fraction * r;
            float lo = float.MaxValue, hi = float.MinValue;
            float previous = 0f;
            int sign = 0, reversals = 0;

            for (int a = 0; a < 720; a++)
            {
                double th = 2.0 * Math.PI * a / 720.0;
                float v = VolcanoCrater.ProfileAt(relief, (float)(Math.Cos(th) * ring),
                                                  (float)(Math.Sin(th) * ring), r, h);
                if (v < lo) lo = v;
                if (v > hi) hi = v;

                if (a > 0)
                {
                    float delta = v - previous;
                    int next = delta > 0f ? 1 : (delta < 0f ? -1 : sign);
                    if (sign != 0 && next != 0 && next != sign) reversals++;
                    sign = next;
                }
                previous = v;
            }

            log.AppendLine("    ring @" + F2(fraction) + "R      : "
                           + (reversals / 2) + " troughs around the circle, "
                           + F1(hi - lo) + " m ridge-to-valley");
        }

        /// <summary>
        /// **溝が「線」として続いているか（本数に依らない指標）。**
        ///
        /// ★★ 2026-08-22。最初に使った「破線度」（陰影を半径方向に歩いて明暗の反転を
        ///   数える）は<b>役に立たなかった</b> —— 対照実験で、谷を 18 本から 36 本へ
        ///   増やしただけの<u>単層</u>の山でも同じ 0.28 を返したからである。
        ///   あれが数えていたのは「溝が途切れているか」ではなく
        ///   **「溝が何本あるか」**で、階段状に歩く自分の足跡を測っていた。
        ///
        /// こちらは<b>本数で割ってある</b>。16 m の環を 1 本ずつ外へ進みながら、
        /// ある環で見つけた谷が**次の環にも同じ方位で在るか**を数える:
        ///
        /// <code>
        /// 1.0 に近い = どの谷も次の環へ続いている ＝ 実線
        /// 低い       = 谷が現れては消える        ＝ 点線
        /// </code>
        ///
        /// 谷は蛇行する（<c>WarpRadians</c>）ので、許容は 1 環あたり弧 2 セルぶん。
        /// </summary>
        private static float GroovePersistence(Field f, float fromFraction, float toFraction)
        {
            int matched = 0;
            int total = 0;

            var previous = new System.Collections.Generic.List<double>();
            var current = new System.Collections.Generic.List<double>();

            for (float d = fromFraction * f.RadiusMetres;
                 d <= toFraction * f.RadiusMetres; d += Cell)
            {
                current.Clear();
                TroughAzimuths(f, d, current);

                if (previous.Count > 0 && current.Count > 0)
                {
                    // 蛇行と 1 セルの丸めを許す（弧 2 セルぶんの角度）。
                    double tolerance = 2.0 * Cell / d;

                    for (int i = 0; i < previous.Count; i++)
                    {
                        total++;
                        for (int j = 0; j < current.Count; j++)
                        {
                            double delta = Math.Abs(previous[i] - current[j]);
                            if (delta > Math.PI) delta = 2.0 * Math.PI - delta;
                            if (delta <= tolerance) { matched++; break; }
                        }
                    }
                }

                previous.Clear();
                previous.AddRange(current);
            }

            return total > 0 ? matched / (float)total : 0f;
        }

        /// <summary>
        /// 半径 <paramref name="d"/> の環を**格子のセルで**読み、谷（極小）の方位を集める。
        /// 解析値ではなく格子に焼いた高さを読むのが要点である
        /// （破線は「溝」と「動かせない 16 m 格子」が噛み合って初めて現れる）。
        /// </summary>
        private static void TroughAzimuths(Field f, float d,
                                           System.Collections.Generic.List<double> into)
        {
            int n = f.Size;
            int half = (n - 1) / 2;

            int steps = (int)(2.0 * Math.PI * d / Cell);
            if (steps < 24) return;

            for (int a = 0; a < steps; a++)
            {
                double th = 2.0 * Math.PI * a / steps;
                double thPrev = 2.0 * Math.PI * (a - 1 + steps) % (2.0 * Math.PI * steps) / steps;
                thPrev = 2.0 * Math.PI * ((a - 1 + steps) % steps) / steps;
                double thNext = 2.0 * Math.PI * ((a + 1) % steps) / steps;

                float here = SampleCell(f, half, d, th);
                float before = SampleCell(f, half, d, thPrev);
                float after = SampleCell(f, half, d, thNext);
                if (here <= 0f) continue;

                // 極小で、かつ両隣より 0.3 m 以上低いものだけを谷と数える
                // （量子化の 1 段や float の丸めを谷にしない）。
                if (before - here >= 0.3f && after - here >= 0.3f) into.Add(th);
            }
        }

        private static float SampleCell(Field f, int half, float d, double th)
        {
            int x = half + (int)Math.Round(Math.Cos(th) * d / Cell);
            int z = half + (int)Math.Round(Math.Sin(th) * d / Cell);
            if (x < 0 || z < 0 || x >= f.Size || z >= f.Size) return 0f;
            return f.At(x, z);
        }

        private static float MinReach(Field f, float r, float h)
        {
            float min = float.MaxValue;
            for (int a = 0; a < 360; a++) min = Math.Min(min, Reach(f, r, h, a));
            return min;
        }

        private static float MaxReach(Field f, float r, float h)
        {
            float max = 0f;
            for (int a = 0; a < 360; a++) max = Math.Max(max, Reach(f, r, h, a));
            return max;
        }

        private static float Reach(Field f, float r, float h, int degrees)
        {
            double th = Math.PI * degrees / 180.0;
            float last = 0f;
            for (float d = 0f; d <= r; d += 2f)
            {
                float v = VolcanoCrater.ProfileAt(f.Relief, (float)(Math.Cos(th) * d),
                                                  (float)(Math.Sin(th) * d), r, h);
                if (v > 0f) last = d;
            }
            return last;
        }

        // ── 隆起アニメーション ────────────────────────────────────

        private static void GrowthFrames(string dir, StringBuilder log)
        {
            const VolcanoForm form = VolcanoForm.Strato;
            float r = VolcanoShape.DefaultRadiusOf(form);
            float h = VolcanoShape.DefaultHeightOf(form);
            Field f = Build(form, r, h, 1f);

            float[] steps = { 0.12f, 0.30f, 0.50f, 0.72f, 1.00f };
            log.AppendLine("## growth (strato, summit-outward)");
            log.AppendLine("  progress | summit m | front m (first cell that reaches 0) | raised cells");

            int n = f.Size;
            var sheet = new byte[(n * steps.Length + (steps.Length - 1) * 2) * n * 3];
            int sheetW = n * steps.Length + (steps.Length - 1) * 2;

            for (int s = 0; s < steps.Length; s++)
            {
                float p = steps[s];
                var frame = new Field
                {
                    Size = n, RadiusMetres = r, HeightMetres = h,
                    H = new float[n * n], Relief = f.Relief
                };

                int raised = 0;
                float front = 0f;
                int half = (n - 1) / 2;
                for (int z = 0; z < n; z++)
                {
                    for (int x = 0; x < n; x++)
                    {
                        float g = UpliftSchedule.GrowthMetresAt(f.H[z * n + x], h, p);
                        frame.H[z * n + x] = g;
                        if (g > 0f)
                        {
                            raised++;
                            float dx = (x - half) * Cell, dz = (z - half) * Cell;
                            float d = (float)Math.Sqrt(dx * dx + dz * dz);
                            if (d > front) front = d;
                        }
                    }
                }

                log.AppendLine("     " + p.ToString("F2", CultureInfo.InvariantCulture)
                               + "   |   " + F1(h * p) + "  |  " + F(front) + "   |  " + raised);

                byte[] small = Shade(frame, h, ContourFor(h, r));
                int zoom = ZoomFor(n);
                Png.Write(Path.Combine(dir, "growth-strato-p" + ((int)(p * 100)).ToString("D3") + ".png"),
                          n * zoom, n * zoom, Upscale(small, n, n, zoom));

                int ox = s * (n + 2);
                for (int z = 0; z < n; z++)
                {
                    for (int x = 0; x < n; x++)
                    {
                        int d = (z * sheetW + ox + x) * 3;
                        int c = (z * n + x) * 3;
                        sheet[d] = small[c]; sheet[d + 1] = small[c + 1]; sheet[d + 2] = small[c + 2];
                    }
                }
            }

            Png.Write(Path.Combine(dir, "growth-strato-sheet.png"), sheetW * 2, n * 2,
                      Upscale(sheet, sheetW, n, 2));
            log.AppendLine();
        }

        // ── 火口（実機の指摘①「最初から窪みとして」）─────────────────────

        /// <summary>
        /// 山頂まわりを拡大して、**隆起の途中の各時刻で火口が窪んでいること**を描いて数える。
        /// 「見た目の変更は自分でオフラインに描画・計測してから実機テストを頼む」の実体である。
        /// </summary>
        private static void CraterFrames(string dir, StringBuilder log)
        {
            const VolcanoForm form = VolcanoForm.Strato;
            float r = VolcanoShape.DefaultRadiusOf(form);
            float h = VolcanoShape.DefaultHeightOf(form);
            var relief = VolcanoRelief.For(form, Seed, 1f);

            float crater = VolcanoShape.CraterRadiusOf(r);
            float depth = VolcanoShape.CraterDepthOf(h);

            log.AppendLine("## crater (strato, part of the profile from the first tick)");
            log.AppendLine("  crater radius = " + F(crater) + " m, depth = " + F(depth)
                           + " m, cone scale = "
                           + VolcanoCrater.SummitScale(form, r).ToString("F3", CultureInfo.InvariantCulture));
            log.AppendLine("  progress | rim m | floor m | depression m | rim ring radius m");

            int half = (int)Math.Ceiling(crater * 2.4f / Cell);
            int n = half * 2 + 1;
            float[] steps = { 0.03f, 0.08f, 0.20f, 0.55f, 1.00f };

            int sheetW = n * steps.Length + (steps.Length - 1) * 2;
            var sheet = new byte[sheetW * n * 3];

            var sections = new float[steps.Length][];
            var colours = new int[steps.Length];
            int[] palette = { 0xB0B0B0, 0x8AA0C8, 0x2F6BE0, 0xE07A2F, 0xE04A2F };

            for (int s = 0; s < steps.Length; s++)
            {
                float p = steps[s];
                var frame = new Field
                {
                    Size = n, RadiusMetres = crater * 2.4f, HeightMetres = h,
                    H = new float[n * n], Relief = relief
                };

                for (int z = 0; z < n; z++)
                {
                    float dz = (z - half) * Cell;
                    for (int x = 0; x < n; x++)
                    {
                        float dx = (x - half) * Cell;
                        frame.H[z * n + x] = UpliftSchedule.GrowthMetresAt(
                            VolcanoCrater.ProfileAt(relief, dx, dz, r, h), h, p);
                    }
                }

                // 縁と底を東西の走査から実測する（式ではなく、描いた高さ場から読む）。
                float rim = 0f, rimAt = 0f;
                for (int x = half; x < n; x++)
                {
                    float v = frame.At(x, half);
                    if (v > rim) { rim = v; rimAt = (x - half) * Cell; }
                }
                float floor = frame.At(half, half);

                log.AppendLine("     " + p.ToString("F2", CultureInfo.InvariantCulture)
                               + "   |  " + F1(rim) + " |  " + F1(floor) + "  |   "
                               + F1(rim - floor) + "   |  " + F(rimAt));

                byte[] small = Shade(frame, rim > 1f ? rim : 1f,
                                     rim > 8f ? rim / 10f : 0f);
                int ox = s * (n + 2);
                for (int z = 0; z < n; z++)
                {
                    for (int x = 0; x < n; x++)
                    {
                        int d = (z * sheetW + ox + x) * 3;
                        int c = (z * n + x) * 3;
                        sheet[d] = small[c]; sheet[d + 1] = small[c + 1]; sheet[d + 2] = small[c + 2];
                    }
                }

                var line = new float[half + 1];
                for (int i = 0; i <= half; i++) line[i] = frame.At(half + i, half);
                sections[s] = line;
                colours[s] = palette[s % palette.Length];
            }

            Png.Write(Path.Combine(dir, "crater-strato-sheet.png"), sheetW * 4, n * 4,
                      Upscale(sheet, sheetW, n, 4));
            Console.WriteLine("wrote " + Path.Combine(dir, "crater-strato-sheet.png"));

            Plot(Path.Combine(dir, "crater-strato-section.png"), h, half * Cell, sections, colours);
            log.AppendLine();
        }

        // ── 断面のグラフ ──────────────────────────────────────────

        private static void Plot(string path, float h, float r, float[][] series, int[] colours)
        {
            const int W = 900, H = 380, PadL = 60, PadB = 34, PadT = 16, PadR = 16;
            var rgb = new byte[W * H * 3];
            for (int i = 0; i < rgb.Length; i++) rgb[i] = 0xFF;

            // 目盛り（100 m ごとの水平線）。
            for (float m = 0; m <= h; m += 100f)
            {
                int y = PadT + (int)((1f - m / h) * (H - PadT - PadB));
                for (int x = PadL; x < W - PadR; x++) Set(rgb, W, x, y, 0xE6E6E6);
            }
            for (int y = PadT; y < H - PadB; y++) Set(rgb, W, PadL, y, 0x404040);
            for (int x = PadL; x < W - PadR; x++) Set(rgb, W, x, H - PadB, 0x404040);

            for (int s = 0; s < series.Length; s++)
            {
                float[] v = series[s];
                int prevX = -1, prevY = -1;
                for (int i = 0; i < v.Length; i++)
                {
                    float d = i * Cell;
                    int x = PadL + (int)(d / r * (W - PadL - PadR));
                    int y = PadT + (int)((1f - v[i] / h) * (H - PadT - PadB));
                    if (prevX >= 0) Line(rgb, W, H, prevX, prevY, x, y, colours[s]);
                    prevX = x; prevY = y;
                }
            }

            Png.Write(path, W, H, rgb);
            Console.WriteLine("wrote " + path);
        }

        private static void Line(byte[] rgb, int w, int h, int x0, int y0, int x1, int y1, int c)
        {
            int dx = Math.Abs(x1 - x0), dy = Math.Abs(y1 - y0);
            int sx = x0 < x1 ? 1 : -1, sy = y0 < y1 ? 1 : -1;
            int err = dx - dy;
            while (true)
            {
                Set(rgb, w, x0, y0, c);
                Set(rgb, w, x0, y0 - 1, c);
                if (x0 == x1 && y0 == y1) break;
                int e2 = err * 2;
                if (e2 > -dy) { err -= dy; x0 += sx; }
                if (e2 < dx) { err += dx; y0 += sy; }
            }
        }

        private static void Set(byte[] rgb, int w, int x, int y, int c)
        {
            if (x < 0 || y < 0 || x >= w) return;
            int i = (y * w + x) * 3;
            if (i < 0 || i + 2 >= rgb.Length) return;
            rgb[i] = (byte)(c >> 16); rgb[i + 1] = (byte)(c >> 8); rgb[i + 2] = (byte)c;
        }

        private static double Deg(double rad) { return rad * 180.0 / Math.PI; }
        private static string F(double v) { return v.ToString("F0", CultureInfo.InvariantCulture); }
        private static string F1(double v) { return v.ToString("F1", CultureInfo.InvariantCulture); }
        private static string F2(double v) { return v.ToString("F2", CultureInfo.InvariantCulture); }
        private static string F3(double v) { return v.ToString("F3", CultureInfo.InvariantCulture); }
        private static string F4(double v) { return v.ToString("F4", CultureInfo.InvariantCulture); }

        /// <summary>
        /// 出来上がった高さ場そのものの極値密度（山の内側だけ）。
        /// <c>Relief.Report</c> が測るのは 1 本のノイズの折り返しで、こちらは
        /// **実際に地形へ書かれる形**が格子の上で折り返していないかである。
        /// </summary>
        private static float ExtremaDensity(Field f)
        {
            int n = f.Size;
            int half = (n - 1) / 2;
            int reversals = 0;
            int counted = 0;

            for (int z = 1; z < n - 1; z++)
            {
                int sign = 0;
                for (int x = 1; x < n - 1; x++)
                {
                    float dz = (z - half) * Cell;
                    float dx = (x - half) * Cell;
                    if (dx * dx + dz * dz > f.RadiusMetres * f.RadiusMetres * 0.81f) { sign = 0; continue; }

                    float delta = f.At(x, z) - f.At(x - 1, z);
                    int next = delta > 0f ? 1 : (delta < 0f ? -1 : sign);
                    if (sign != 0 && next != 0 && next != sign) reversals++;
                    if (sign != 0) counted++;
                    sign = next;
                }
            }

            return counted > 0 ? reversals / (float)counted : 0f;
        }
    }

    internal static class ReliefText
    {
        public static string GulliesText(this VolcanoRelief r, float radius)
        {
            float spacing = (float)(2.0 * Math.PI * 0.55 * radius / r.GullyCount);
            return r.GullyCount + " channels, ~" + spacing.ToString("F0", CultureInfo.InvariantCulture)
                   + " m apart at 0.55R";
        }

        public static string RillsText(this VolcanoRelief r, float radius)
        {
            float onset = r.RillOnsetRadiusMetres;
            float spacing = (float)(2.0 * Math.PI * 0.85 * radius / r.RillCount);
            if (!r.RillsFitOn(radius))
            {
                return r.RillCount + " would only fit outside "
                       + onset.ToString("F0", CultureInfo.InvariantCulture)
                       + " m, too thin a ring, so NONE are drawn (16 m grid)";
            }
            return r.RillCount + " rills, ~" + spacing.ToString("F0", CultureInfo.InvariantCulture)
                   + " m apart at 0.85R, full depth only beyond "
                   + onset.ToString("F0", CultureInfo.InvariantCulture) + " m ("
                   + (onset / radius).ToString("F2", CultureInfo.InvariantCulture) + "R)";
        }
    }
}
