using System;
using System.IO;
using System.Text;
using DisasterPlus.Core.Common;
using DisasterPlus.Core.Volcano;
using DisasterPlus.Tools;

namespace DisasterPlus.Tools.CraterPreview
{
    /// <summary>
    /// Draws and checks the crater's magma pool, the light it casts on the plume, and the
    /// lightning inside the plume, **without launching the game** (2026-08-22, at the owner's
    /// request).
    ///
    /// This is the tool for this project's rule that "visual changes are drawn and measured
    /// offline by yourself before asking for a test in the game". It compiles and calls
    /// <b>the real thing from Core</b> directly, so it is not a rewritten approximation.
    ///
    ///   dotnet run --project tools/CraterPreview -- docs/images/volcano
    /// </summary>
    internal static class Program
    {
        /// <summary>Horizontal (m). Shows 6 times the crater radius of 144 m (0.12 of a
        /// 1200 m stratovolcano).</summary>
        private const float ViewHalfWidthMetres = 900f;

        /// <summary>Vertical (m). Up to 0.8 of the column height.</summary>
        private const float ViewHeightMetres = 1400f;

        private const int Width = 900;
        private const int Height = 700;

        private const float CraterRadiusMetres = 144f;
        private const float PlumeHeightMetres = 1600f;

        private static int Main(string[] args)
        {
            string outDir = args.Length > 0 ? args[0] : "docs/images/volcano";
            Directory.CreateDirectory(outDir);

            var log = new StringBuilder();
            log.AppendLine("# Crater glow / plume light / volcanic lightning preview");
            log.AppendLine("# (generated by tools/CraterPreview, calling the real Core code)");
            log.AppendLine();

            Strobe(log);
            Reach(log);
            Bolts(log);
            LavaWidth(log);
            Scene(outDir, log);

            File.WriteAllText(Path.Combine(outDir, "crater-measurements.txt"), log.ToString());
            Console.Write(log.ToString());
            return 0;
        }

        // ── 1. That it does not strobe ────────────────────────────────

        private static void Strobe(StringBuilder log)
        {
            log.AppendLine("## pool brightness (must not strobe - LavaGlow was corrected once)");

            const float Step = 1f / 60f;
            float previous = CraterGlow.PoolBrightness(1f, 0f);
            float worst = 0f;
            float lo = previous, hi = previous;

            for (int i = 1; i <= 60 * 30; i++)
            {
                float now = CraterGlow.PoolBrightness(1f, i * Step);
                float d = Math.Abs(now - previous);
                if (d > worst) worst = d;
                if (now < lo) lo = now;
                if (now > hi) hi = now;
                previous = now;
            }

            log.AppendLine("  30 s at 60 fps: range " + lo.ToString("F3") + " .. " + hi.ToString("F3")
                           + "   worst per-frame step " + worst.ToString("F5"));
            log.AppendLine();
        }

        // ── 2. How far the light reaches ────────────────────────────────

        private static void Reach(StringBuilder log)
        {
            log.AppendLine("## light on the plume (0 at " + CraterGlow.ReachFraction.ToString("F2")
                           + " of the column height)");
            log.AppendLine("  height m | fraction | light");

            float b = CraterGlow.PoolBrightness(1f, 4f);
            foreach (float f in new[] { 0f, 0.05f, 0.10f, 0.20f, 0.30f, 0.34f, 0.50f, 1f })
            {
                float y = PlumeHeightMetres * f;
                log.AppendLine("  " + y.ToString("F0").PadLeft(8) + " | " + f.ToString("F2").PadLeft(8)
                               + " | " + CraterGlow.LightAt(y, PlumeHeightMetres, b).ToString("F3"));
            }
            log.AppendLine();
        }

        // ── 3. The frequency and size of the lightning ─────────────────────────────────

        private static void Bolts(StringBuilder log)
        {
            uint seed = DeterministicRandom.Hash(4242u, 909u);

            log.AppendLine("## lightning (slot " + PlumeLightning.SlotSeconds
                           + " s, flash " + PlumeLightning.FlashSeconds + " s)");
            log.AppendLine("  strength | flashes in 60 s | visible frames | mean peak");

            foreach (float unit in new[] { 0.2f, 0.6f, 1.0f })
            {
                int lit = 0;
                int flashes = 0;
                double peakSum = 0;

                for (int slot = 0; slot < (int)(60f / PlumeLightning.SlotSeconds); slot++)
                {
                    float peak = 0f;
                    for (int k = 0; k < 40; k++)
                    {
                        float t = PlumeLightning.StartOf(seed, slot)
                                  + PlumeLightning.FlashSeconds * k / 40f;
                        float b = PlumeLightning.BrightnessAt(seed, slot, t, unit);
                        if (b > 0.02f) lit++;
                        if (b > peak) peak = b;
                    }
                    if (peak > 0.02f)
                    {
                        flashes++;
                        peakSum += peak;
                    }
                }

                log.AppendLine("  " + unit.ToString("F1").PadLeft(8) + " | " + flashes.ToString().PadLeft(15)
                               + " | " + lit.ToString().PadLeft(14) + " | "
                               + (flashes > 0 ? (peakSum / flashes).ToString("F3") : "-"));
            }
            log.AppendLine();
        }

        // ── 3b. The width of the lava flow ──────────────────────────────

        private static void LavaWidth(StringBuilder log)
        {
            log.AppendLine("## lava band width (diameter = 2 x spread radius)");
            log.AppendLine("  volcano r | factor | at vent m | at 1 km m | at the cap m");

            foreach (float r in new[] { 400f, 1200f, 2000f, 3000f })
            {
                float f = LavaVolume.WidthFactor(r);
                log.AppendLine("  " + r.ToString("F0").PadLeft(9)
                               + " | " + f.ToString("F2").PadLeft(6)
                               + " | " + (LavaPath.SpreadRadiusFor(0f, f) * 2f).ToString("F0").PadLeft(9)
                               + " | " + (LavaPath.SpreadRadiusFor(1000f, f) * 2f).ToString("F0").PadLeft(9)
                               + " | " + (LavaPath.SpreadRadiusFor(100000f, f) * 2f).ToString("F0").PadLeft(12));
            }

            log.AppendLine("  (before 2026-08-22: 40 m at the vent, 120 m at the cap, no scaling)");
            log.AppendLine();
        }

        // ── 4. The picture (a cross-section seen from the side) ────────────────────────────

        private static void Scene(string dir, StringBuilder log)
        {
            var rgb = new byte[Width * Height * 3];
            Fill(rgb, 14, 16, 22);

            var column = new EruptionColumn(CraterRadiusMetres, 1f, 1f, 0f, 12f);
            uint seed = DeterministicRandom.Hash(4242u, 909u);

            // The column's outline (faint grey), so it can be seen by eye that the lightning
            // stays inside it.
            for (int py = 0; py < Height; py++)
            {
                float y = MetresY(py);
                if (y < 0f || y > column.HeightMetres) continue;

                float r = column.RadiusAt(y);
                for (int px = 0; px < Width; px++)
                {
                    float x = MetresX(px);
                    if (Math.Abs(x) <= r) Add(rgb, px, py, 26, 28, 34);
                }
            }

            // The magma pool (seen from the side, so it is drawn as a band at the crater floor).
            float b0 = CraterGlow.PoolBrightness(1f, 4f);
            float poolR = CraterGlow.PoolRadiusMetres(CraterRadiusMetres, 1f);
            for (int px = 0; px < Width; px++)
            {
                float x = MetresX(px);
                if (Math.Abs(x) > poolR) continue;

                float across = 1f - Math.Abs(x) / poolR;
                float k = b0 * across * across;
                for (int py = YPixel(6f); py <= YPixel(0f) && py < Height; py++)
                {
                    Add(rgb, px, py, (byte)(255 * k), (byte)(255 * k * 0.42f), (byte)(255 * k * 0.12f));
                }
            }

            // The light on the plume (spreading sideways with height).
            for (int py = 0; py < Height; py++)
            {
                float y = MetresY(py);
                if (y < 0f) continue;

                float k = CraterGlow.LightAt(y, column.HeightMetres, b0);
                if (k <= 0.004f) continue;

                float spread = poolR * (1f + 1.6f * (y / (column.HeightMetres * CraterGlow.ReachFraction)));
                for (int px = 0; px < Width; px++)
                {
                    float x = MetresX(px);
                    if (Math.Abs(x) > spread) continue;

                    float across = 1f - Math.Abs(x) / spread;
                    float a = k * across;
                    Add(rgb, px, py, (byte)(255 * a), (byte)(255 * a * 0.42f), (byte)(255 * a * 0.12f));
                }
            }

            // Six bolts, overlaid at their brightest moment.
            var path = new LightningPoint[PlumeLightning.PointCount];
            EruptionColumn shape = column;
            float height = shape.HeightMetres;
            RadiusAtFraction radiusAt = delegate(float f) { return shape.RadiusAt(height * f); };

            int drawn = 0;
            for (int slot = 0; slot < 6; slot++)
            {
                int n = PlumeLightning.PathInto(path, seed, slot, height, radiusAt);
                if (n < 2) continue;

                float peak = PlumeLightning.BrightnessAt(
                    seed, slot, PlumeLightning.StartOf(seed, slot) + 0.001f, 1f);

                for (int i = 0; i < n - 1; i++)
                {
                    Line(rgb, path[i].X, path[i].Y, path[i + 1].X, path[i + 1].Y, peak);
                }
                drawn++;
            }

            log.AppendLine("## scene: crater r=" + CraterRadiusMetres + " m, column h="
                           + height.ToString("F0") + " m, pool r=" + poolR.ToString("F0")
                           + " m, " + drawn + " bolts drawn");
            log.AppendLine();

            Png.Write(Path.Combine(dir, "crater-glow-preview.png"), Width, Height, rgb);
        }

        // ── Coordinates ───────────────────────────────────────────

        private static float MetresX(int px)
        {
            return (px / (float)(Width - 1)) * (2f * ViewHalfWidthMetres) - ViewHalfWidthMetres;
        }

        private static float MetresY(int py)
        {
            return (1f - py / (float)(Height - 1)) * ViewHeightMetres;
        }

        private static int XPixel(float metres)
        {
            return (int)Math.Round((metres + ViewHalfWidthMetres) / (2f * ViewHalfWidthMetres) * (Width - 1));
        }

        private static int YPixel(float metres)
        {
            return (int)Math.Round((1f - metres / ViewHeightMetres) * (Height - 1));
        }

        private static void Line(byte[] rgb, float x0, float y0, float x1, float y1, float k)
        {
            int ax = XPixel(x0), ay = YPixel(y0);
            int bx = XPixel(x1), by = YPixel(y1);

            int steps = Math.Max(Math.Abs(bx - ax), Math.Abs(by - ay));
            if (steps <= 0) steps = 1;

            for (int i = 0; i <= steps; i++)
            {
                float t = i / (float)steps;
                int px = (int)Math.Round(ax + (bx - ax) * t);
                int py = (int)Math.Round(ay + (by - ay) * t);

                for (int dx = -1; dx <= 1; dx++)
                {
                    for (int dy = -1; dy <= 1; dy++)
                    {
                        float edge = (dx == 0 && dy == 0) ? 1f : 0.35f;
                        float a = k * edge;
                        Add(rgb, px + dx, py + dy,
                            (byte)(255 * a * 0.82f), (byte)(255 * a * 0.88f), (byte)(255 * a));
                    }
                }
            }
        }

        private static void Fill(byte[] rgb, byte r, byte g, byte b)
        {
            for (int i = 0; i < rgb.Length; i += 3)
            {
                rgb[i] = r;
                rgb[i + 1] = g;
                rgb[i + 2] = b;
            }
        }

        /// <summary>Additive compositing. The game side is additive too, so it looks the
        /// same.</summary>
        private static void Add(byte[] rgb, int x, int y, byte r, byte g, byte b)
        {
            if (x < 0 || x >= Width || y < 0 || y >= Height) return;

            int i = (y * Width + x) * 3;
            rgb[i] = (byte)Math.Min(255, rgb[i] + r);
            rgb[i + 1] = (byte)Math.Min(255, rgb[i + 1] + g);
            rgb[i + 2] = (byte)Math.Min(255, rgb[i + 2] + b);
        }
    }
}
