# en.txt をビルド済み DLL のリフレクションで生成する。手書きテンプレートは黙って乖離する。
#
# Strings クラス自体は他アセンブリに依存しない純粋な文字列定数の集まりなので、
# 型ロードには UnityEngine / ColossalManaged / ICities の存在確認だけで足りる
# （Assembly-CSharp や CitiesHarmony 系は他の型を触ったときに初めて解決される）。
# 実測済み: この最小プリロードで RESOLVE MISS は発生しない。
#
# 注意: AssemblyResolve ハンドラの中で LoadFrom を呼んではいけない（無限再帰で
# StackOverflow になる）。未知のアセンブリは null を返して素通りさせる。
$ErrorActionPreference = "Stop"
$dll = Resolve-Path "src\DisasterPlus\bin\Release\DisasterPlus.dll"
$managed = if ($env:CITIES_SKYLINES_MANAGED) { $env:CITIES_SKYLINES_MANAGED }
           else { "C:\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed" }

$preloaded = @{}
foreach ($n in @('UnityEngine','ColossalManaged','ICities')) {
    $f = Join-Path $managed ($n + '.dll')
    if (Test-Path $f) { $a = [Reflection.Assembly]::LoadFrom($f); $preloaded[$a.GetName().Name] = $a }
}
[AppDomain]::CurrentDomain.add_AssemblyResolve({
    param($s, $e)
    $n = (New-Object Reflection.AssemblyName $e.Name).Name
    if ($preloaded.ContainsKey($n)) { return $preloaded[$n] }
    return $null
})

$asm = [Reflection.Assembly]::LoadFrom($dll)
$t = $asm.GetType('DisasterPlus.Game.Strings')
if (-not $t) { throw "DisasterPlus.Game.Strings not found in $dll" }

# Locales\*.txt はランタイムの LocaleLoader が File.ReadAllLines(path, Encoding.UTF8) で
# 読む。BOM を付けると先頭キー名が壊れるので、ここは必ず BOM 無し UTF-8 で書く
# （このスクリプト自身は日本語コメントを含むので BOM 付きで保存しておくこと。逆にしない）。
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Disaster + - English template (generated by tools\GenerateLocaleTemplate.ps1).")
$lines.Add("# Copy to <lang>.txt and translate the right-hand side. Use \n for line breaks.")
foreach ($f in $t.GetFields('Public,Static')) {
    if ($f.FieldType -ne [string]) { continue }
    $lines.Add($f.Name + " = " + ($f.GetValue($null) -replace "`n", "\n"))
}
[IO.File]::WriteAllLines((Join-Path (Get-Location) "Locales\en.txt"), $lines,
                         (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote Locales\en.txt ($($lines.Count - 2) keys)"
