# Generate en.txt by reflecting over the built DLL. A hand-written template drifts silently.
#
# The Strings class itself is a pure collection of string constants that depends on no other
# assembly, so loading the type only needs UnityEngine / ColossalManaged / ICities to be
# present (Assembly-CSharp and the CitiesHarmony assemblies are not resolved until some other
# type is touched).
# Measured: with this minimal preload no RESOLVE MISS occurs.
#
# Note: never call LoadFrom inside the AssemblyResolve handler (it recurses without end and
# becomes a StackOverflow). Return null for unknown assemblies and let them pass through.
$ErrorActionPreference = "Stop"
$dll = Resolve-Path "src\DisasterPlus\bin\Release\DisasterPlus.dll"
$managed = if ($env:CITIES_SKYLINES_MANAGED) { $env:CITIES_SKYLINES_MANAGED }
           else { "C:\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed" }

$preloaded = @{}
foreach ($n in @('UnityEngine','ColossalManaged','ICities')) {
    $f = Join-Path $managed ($n + '.dll')
    if (Test-Path $f) { $a = [Reflection.Assembly]::LoadFrom($f); $preloaded[$a.GetName().Name] = $a }
}
[AppDomain]::CurrentDomain.add_AssemblyResolve({
    param($s, $e)
    $n = (New-Object Reflection.AssemblyName $e.Name).Name
    if ($preloaded.ContainsKey($n)) { return $preloaded[$n] }
    return $null
})

$asm = [Reflection.Assembly]::LoadFrom($dll)
$t = $asm.GetType('DisasterPlus.Game.Strings')
if (-not $t) { throw "DisasterPlus.Game.Strings not found in $dll" }

# Locales\*.txt is read at run time by LocaleLoader via
# File.ReadAllLines(path, Encoding.UTF8). A BOM would corrupt the first key name, so this must
# always be written as UTF-8 without a BOM (this script itself is to be saved WITH a BOM. Do
# not get the two the wrong way round).
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Disaster + - English template (generated by tools\GenerateLocaleTemplate.ps1).")
$lines.Add("# Copy to <lang>.txt and translate the right-hand side. Use \n for line breaks.")
foreach ($f in $t.GetFields('Public,Static')) {
    if ($f.FieldType -ne [string]) { continue }
    $lines.Add($f.Name + " = " + ($f.GetValue($null) -replace "`n", "\n"))
}
[IO.File]::WriteAllLines((Join-Path (Get-Location) "Locales\en.txt"), $lines,
                         (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote Locales\en.txt ($($lines.Count - 2) keys)"
